// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: browse.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearTrackOverride = `-- name: ClearTrackOverride :exec
DELETE FROM track_overrides WHERE track_id = $1
`

func (q *Queries) ClearTrackOverride(ctx context.Context, trackID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearTrackOverride, trackID)
	return err
}

const getAlbum = `-- name: GetAlbum :one
SELECT al.id, al.name, al.year, al.cover_art_id,
       ar.id AS artist_id, COALESCE(ar.name, '')::text AS artist_name,
       count(t.id)::bigint AS track_count,
       COALESCE(sum(t.duration_ms), 0)::bigint AS duration_ms
FROM albums al
LEFT JOIN artists ar ON ar.id = al.album_artist_id
LEFT JOIN tracks t ON t.album_id = al.id AND t.missing_at IS NULL
WHERE al.id = $1
GROUP BY al.id, al.name, al.year, al.cover_art_id, ar.id, ar.name
`

type GetAlbumRow struct {
	ID         uuid.UUID
	Name       string
	Year       *int32
	CoverArtID pgtype.UUID
	ArtistID   pgtype.UUID
	ArtistName string
	TrackCount int64
	DurationMs int64
}

func (q *Queries) GetAlbum(ctx context.Context, id uuid.UUID) (GetAlbumRow, error) {
	row := q.db.QueryRow(ctx, getAlbum, id)
	var i GetAlbumRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Year,
		&i.CoverArtID,
		&i.ArtistID,
		&i.ArtistName,
		&i.TrackCount,
		&i.DurationMs,
	)
	return i, err
}

const getArtist = `-- name: GetArtist :one
SELECT ar.id, ar.name,
       count(DISTINCT t.id)::bigint AS track_count,
       count(DISTINCT t.album_id)::bigint AS album_count
FROM artists ar
LEFT JOIN tracks t ON (t.artist_id = ar.id OR t.album_artist_id = ar.id) AND t.missing_at IS NULL
WHERE ar.id = $1
GROUP BY ar.id, ar.name
`

type GetArtistRow struct {
	ID         uuid.UUID
	Name       string
	TrackCount int64
	AlbumCount int64
}

func (q *Queries) GetArtist(ctx context.Context, id uuid.UUID) (GetArtistRow, error) {
	row := q.db.QueryRow(ctx, getArtist, id)
	var i GetArtistRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TrackCount,
		&i.AlbumCount,
	)
	return i, err
}

const getTrack = `-- name: GetTrack :one
SELECT te.id, te.root_id, te.rel_path, te.size, te.mtime, te.content_hash, te.duration_ms, te.bitrate, te.sample_rate, te.channels, te.codec, te.suffix, te.album_id, te.artist_id, te.album_artist_id, te.cover_art_id, te.missing_at, te.created_at, te.updated_at, te.title, te.track_no, te.disc_no, te.year, te.artist_name, te.album_name, te.album_artist_name,
       (SELECT COALESCE(array_agg(g.name ORDER BY g.name), '{}')
        FROM track_genres tg JOIN genres g ON g.id = tg.genre_id
        WHERE tg.track_id = te.id)::text[] AS genres
FROM tracks_effective te
WHERE te.id = $1
`

type GetTrackRow struct {
	ID              uuid.UUID
	RootID          uuid.UUID
	RelPath         string
	Size            int64
	Mtime           time.Time
	ContentHash     []byte
	DurationMs      *int32
	Bitrate         *int32
	SampleRate      *int32
	Channels        *int16
	Codec           *string
	Suffix          string
	AlbumID         pgtype.UUID
	ArtistID        pgtype.UUID
	AlbumArtistID   pgtype.UUID
	CoverArtID      pgtype.UUID
	MissingAt       pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Title           string
	TrackNo         *int32
	DiscNo          *int32
	Year            *int32
	ArtistName      string
	AlbumName       string
	AlbumArtistName string
	Genres          []string
}

func (q *Queries) GetTrack(ctx context.Context, id uuid.UUID) (GetTrackRow, error) {
	row := q.db.QueryRow(ctx, getTrack, id)
	var i GetTrackRow
	err := row.Scan(
		&i.ID,
		&i.RootID,
		&i.RelPath,
		&i.Size,
		&i.Mtime,
		&i.ContentHash,
		&i.DurationMs,
		&i.Bitrate,
		&i.SampleRate,
		&i.Channels,
		&i.Codec,
		&i.Suffix,
		&i.AlbumID,
		&i.ArtistID,
		&i.AlbumArtistID,
		&i.CoverArtID,
		&i.MissingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.TrackNo,
		&i.DiscNo,
		&i.Year,
		&i.ArtistName,
		&i.AlbumName,
		&i.AlbumArtistName,
		&i.Genres,
	)
	return i, err
}

const listAlbumTracks = `-- name: ListAlbumTracks :many
SELECT te.id, te.root_id, te.rel_path, te.size, te.mtime, te.content_hash, te.duration_ms, te.bitrate, te.sample_rate, te.channels, te.codec, te.suffix, te.album_id, te.artist_id, te.album_artist_id, te.cover_art_id, te.missing_at, te.created_at, te.updated_at, te.title, te.track_no, te.disc_no, te.year, te.artist_name, te.album_name, te.album_artist_name,
       (SELECT COALESCE(array_agg(g.name ORDER BY g.name), '{}')
        FROM track_genres tg JOIN genres g ON g.id = tg.genre_id
        WHERE tg.track_id = te.id)::text[] AS genres
FROM tracks_effective te
WHERE te.album_id = $1 AND te.missing_at IS NULL
ORDER BY COALESCE(te.disc_no, 1), COALESCE(te.track_no, 0), lower(te.title)
`

type ListAlbumTracksRow struct {
	ID              uuid.UUID
	RootID          uuid.UUID
	RelPath         string
	Size            int64
	Mtime           time.Time
	ContentHash     []byte
	DurationMs      *int32
	Bitrate         *int32
	SampleRate      *int32
	Channels        *int16
	Codec           *string
	Suffix          string
	AlbumID         pgtype.UUID
	ArtistID        pgtype.UUID
	AlbumArtistID   pgtype.UUID
	CoverArtID      pgtype.UUID
	MissingAt       pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Title           string
	TrackNo         *int32
	DiscNo          *int32
	Year            *int32
	ArtistName      string
	AlbumName       string
	AlbumArtistName string
	Genres          []string
}

// Disc then track number, which is the only order an album makes sense in.
func (q *Queries) ListAlbumTracks(ctx context.Context, albumID pgtype.UUID) ([]ListAlbumTracksRow, error) {
	rows, err := q.db.Query(ctx, listAlbumTracks, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlbumTracksRow{}
	for rows.Next() {
		var i ListAlbumTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.RootID,
			&i.RelPath,
			&i.Size,
			&i.Mtime,
			&i.ContentHash,
			&i.DurationMs,
			&i.Bitrate,
			&i.SampleRate,
			&i.Channels,
			&i.Codec,
			&i.Suffix,
			&i.AlbumID,
			&i.ArtistID,
			&i.AlbumArtistID,
			&i.CoverArtID,
			&i.MissingAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.TrackNo,
			&i.DiscNo,
			&i.Year,
			&i.ArtistName,
			&i.AlbumName,
			&i.AlbumArtistName,
			&i.Genres,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbums = `-- name: ListAlbums :many

SELECT al.id, al.name, al.year, al.cover_art_id,
       ar.id AS artist_id, COALESCE(ar.name, '')::text AS artist_name,
       count(t.id)::bigint AS track_count,
       COALESCE(sum(t.duration_ms), 0)::bigint AS duration_ms
FROM albums al
LEFT JOIN artists ar ON ar.id = al.album_artist_id
JOIN tracks t ON t.album_id = al.id AND t.missing_at IS NULL
WHERE ($2::uuid IS NULL OR al.album_artist_id = $2::uuid)
  AND ($3::int IS NULL OR al.year = $3::int)
  AND ($4::text IS NULL OR EXISTS (
        SELECT 1 FROM track_genres tg JOIN genres g ON g.id = tg.genre_id
        WHERE tg.track_id = t.id AND g.name = $4::citext))
  AND ($5::text IS NULL
       OR (lower(al.name), al.id) > ($5::text, $6::uuid))
GROUP BY al.id, al.name, al.year, al.cover_art_id, ar.id, ar.name
ORDER BY lower(al.name), al.id
LIMIT $1
`

type ListAlbumsParams struct {
	Limit      int32
	ArtistID   pgtype.UUID
	Year       *int32
	Genre      *string
	CursorSort *string
	CursorID   pgtype.UUID
}

type ListAlbumsRow struct {
	ID         uuid.UUID
	Name       string
	Year       *int32
	CoverArtID pgtype.UUID
	ArtistID   pgtype.UUID
	ArtistName string
	TrackCount int64
	DurationMs int64
}

// ---- albums -------------------------------------------------------------------
func (q *Queries) ListAlbums(ctx context.Context, arg ListAlbumsParams) ([]ListAlbumsRow, error) {
	rows, err := q.db.Query(ctx, listAlbums,
		arg.Limit,
		arg.ArtistID,
		arg.Year,
		arg.Genre,
		arg.CursorSort,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlbumsRow{}
	for rows.Next() {
		var i ListAlbumsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Year,
			&i.CoverArtID,
			&i.ArtistID,
			&i.ArtistName,
			&i.TrackCount,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtists = `-- name: ListArtists :many

SELECT ar.id, ar.name,
       count(DISTINCT t.id)::bigint AS track_count,
       count(DISTINCT t.album_id)::bigint AS album_count
FROM artists ar
JOIN tracks t ON (t.artist_id = ar.id OR t.album_artist_id = ar.id) AND t.missing_at IS NULL
WHERE ($2::text IS NULL
       OR (ar.norm_name, ar.id) > ($2::text, $3::uuid))
GROUP BY ar.id, ar.name, ar.norm_name
ORDER BY ar.norm_name, ar.id
LIMIT $1
`

type ListArtistsParams struct {
	Limit      int32
	CursorSort *string
	CursorID   pgtype.UUID
}

type ListArtistsRow struct {
	ID         uuid.UUID
	Name       string
	TrackCount int64
	AlbumCount int64
}

// ---- artists ------------------------------------------------------------------
// Only artists with at least one live track: reconciliation can leave rows
// behind, and a browse list full of entries that match nothing is noise.
func (q *Queries) ListArtists(ctx context.Context, arg ListArtistsParams) ([]ListArtistsRow, error) {
	rows, err := q.db.Query(ctx, listArtists, arg.Limit, arg.CursorSort, arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtistsRow{}
	for rows.Next() {
		var i ListArtistsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TrackCount,
			&i.AlbumCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenres = `-- name: ListGenres :many

SELECT g.id, g.name::text AS name, count(t.id)::bigint AS track_count
FROM genres g
JOIN track_genres tg ON tg.genre_id = g.id
JOIN tracks t ON t.id = tg.track_id AND t.missing_at IS NULL
GROUP BY g.id, g.name
ORDER BY g.name
`

type ListGenresRow struct {
	ID         uuid.UUID
	Name       string
	TrackCount int64
}

// ---- genres -------------------------------------------------------------------
func (q *Queries) ListGenres(ctx context.Context) ([]ListGenresRow, error) {
	rows, err := q.db.Query(ctx, listGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGenresRow{}
	for rows.Next() {
		var i ListGenresRow
		if err := rows.Scan(&i.ID, &i.Name, &i.TrackCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracks = `-- name: ListTracks :many


SELECT te.id, te.root_id, te.rel_path, te.size, te.mtime, te.content_hash, te.duration_ms, te.bitrate, te.sample_rate, te.channels, te.codec, te.suffix, te.album_id, te.artist_id, te.album_artist_id, te.cover_art_id, te.missing_at, te.created_at, te.updated_at, te.title, te.track_no, te.disc_no, te.year, te.artist_name, te.album_name, te.album_artist_name,
       (SELECT COALESCE(array_agg(g.name ORDER BY g.name), '{}')
        FROM track_genres tg JOIN genres g ON g.id = tg.genre_id
        WHERE tg.track_id = te.id)::text[] AS genres
FROM tracks_effective te
WHERE te.missing_at IS NULL
  AND ($2::uuid IS NULL
       OR te.artist_id = $2::uuid
       OR te.album_artist_id = $2::uuid)
  AND ($3::uuid IS NULL OR te.album_id = $3::uuid)
  AND ($4::int IS NULL OR te.year = $4::int)
  AND ($5::text IS NULL OR EXISTS (
        SELECT 1 FROM track_genres tg JOIN genres g ON g.id = tg.genre_id
        WHERE tg.track_id = te.id AND g.name = $5::citext))
  AND ($6::text IS NULL
       OR (lower(te.title), te.id) > ($6::text, $7::uuid))
ORDER BY lower(te.title), te.id
LIMIT $1
`

type ListTracksParams struct {
	Limit      int32
	ArtistID   pgtype.UUID
	AlbumID    pgtype.UUID
	Year       *int32
	Genre      *string
	CursorSort *string
	CursorID   pgtype.UUID
}

type ListTracksRow struct {
	ID              uuid.UUID
	RootID          uuid.UUID
	RelPath         string
	Size            int64
	Mtime           time.Time
	ContentHash     []byte
	DurationMs      *int32
	Bitrate         *int32
	SampleRate      *int32
	Channels        *int16
	Codec           *string
	Suffix          string
	AlbumID         pgtype.UUID
	ArtistID        pgtype.UUID
	AlbumArtistID   pgtype.UUID
	CoverArtID      pgtype.UUID
	MissingAt       pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Title           string
	TrackNo         *int32
	DiscNo          *int32
	Year            *int32
	ArtistName      string
	AlbumName       string
	AlbumArtistName string
	Genres          []string
}

// Read paths for browsing and searching the library.
//
// Every listing is keyset-paginated on (sort key, id). Offset pagination
// degrades badly past a few thousand rows and double-serves items when the
// library changes mid-scroll, which it does constantly while a scan runs.
// ---- tracks -------------------------------------------------------------------
// The one query behind GET /tracks. Each filter is inert when its parameter is
// NULL, so one statement serves every combination the API allows rather than a
// combinatorial set of near-identical queries.
//
// The cursor predicate is a row comparison rather than OR-ed inequalities:
// (sort_key, id) > (last_sort_key, last_id) uses the composite index directly,
// where the expanded form usually will not.
func (q *Queries) ListTracks(ctx context.Context, arg ListTracksParams) ([]ListTracksRow, error) {
	rows, err := q.db.Query(ctx, listTracks,
		arg.Limit,
		arg.ArtistID,
		arg.AlbumID,
		arg.Year,
		arg.Genre,
		arg.CursorSort,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTracksRow{}
	for rows.Next() {
		var i ListTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.RootID,
			&i.RelPath,
			&i.Size,
			&i.Mtime,
			&i.ContentHash,
			&i.DurationMs,
			&i.Bitrate,
			&i.SampleRate,
			&i.Channels,
			&i.Codec,
			&i.Suffix,
			&i.AlbumID,
			&i.ArtistID,
			&i.AlbumArtistID,
			&i.CoverArtID,
			&i.MissingAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.TrackNo,
			&i.DiscNo,
			&i.Year,
			&i.ArtistName,
			&i.AlbumName,
			&i.AlbumArtistName,
			&i.Genres,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rebuildTrackSearch = `-- name: RebuildTrackSearch :exec
INSERT INTO track_search (track_id, haystack)
SELECT te.id,
       concat_ws(' ', NULLIF(te.title, ''), NULLIF(te.artist_name, ''),
                 NULLIF(te.album_name, ''), NULLIF(te.album_artist_name, ''),
                 (SELECT string_agg(g.name::text, ' ' ORDER BY g.name)
                  FROM track_genres tg JOIN genres g ON g.id = tg.genre_id
                  WHERE tg.track_id = te.id))
FROM tracks_effective te
WHERE te.id = $1
ON CONFLICT (track_id) DO UPDATE SET haystack = EXCLUDED.haystack
`

// Rebuilds a track's search text from its effective values.
//
// This is the single definition of the haystack, used by both the scanner and
// the override editor. Assembling it in Go as well would let the two drift, and
// the symptom would be a track that is unfindable by the name shown for it.
func (q *Queries) RebuildTrackSearch(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, rebuildTrackSearch, id)
	return err
}

const searchAlbums = `-- name: SearchAlbums :many
SELECT al.id, al.name, al.year, al.cover_art_id,
       COALESCE(ar.name, '')::text AS artist_name,
       word_similarity($2::text, al.norm_name) AS rank
FROM albums al
LEFT JOIN artists ar ON ar.id = al.album_artist_id
WHERE EXISTS (SELECT 1 FROM tracks t WHERE t.album_id = al.id AND t.missing_at IS NULL)
  AND ($2::text <% al.norm_name OR al.norm_name ILIKE '%' || $2::text || '%')
ORDER BY rank DESC, lower(al.name)
LIMIT $1
`

type SearchAlbumsParams struct {
	Limit int32
	Query string
}

type SearchAlbumsRow struct {
	ID         uuid.UUID
	Name       string
	Year       *int32
	CoverArtID pgtype.UUID
	ArtistName string
	Rank       float32
}

func (q *Queries) SearchAlbums(ctx context.Context, arg SearchAlbumsParams) ([]SearchAlbumsRow, error) {
	rows, err := q.db.Query(ctx, searchAlbums, arg.Limit, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchAlbumsRow{}
	for rows.Next() {
		var i SearchAlbumsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Year,
			&i.CoverArtID,
			&i.ArtistName,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchArtists = `-- name: SearchArtists :many
SELECT ar.id, ar.name,
       word_similarity($2::text, ar.norm_name) AS rank
FROM artists ar
WHERE EXISTS (SELECT 1 FROM tracks t
              WHERE (t.artist_id = ar.id OR t.album_artist_id = ar.id) AND t.missing_at IS NULL)
  AND ($2::text <% ar.norm_name OR ar.norm_name ILIKE '%' || $2::text || '%')
ORDER BY rank DESC, lower(ar.name)
LIMIT $1
`

type SearchArtistsParams struct {
	Limit int32
	Query string
}

type SearchArtistsRow struct {
	ID   uuid.UUID
	Name string
	Rank float32
}

func (q *Queries) SearchArtists(ctx context.Context, arg SearchArtistsParams) ([]SearchArtistsRow, error) {
	rows, err := q.db.Query(ctx, searchArtists, arg.Limit, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchArtistsRow{}
	for rows.Next() {
		var i SearchArtistsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Rank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTracksExact = `-- name: SearchTracksExact :many

SELECT te.id, te.root_id, te.rel_path, te.size, te.mtime, te.content_hash, te.duration_ms, te.bitrate, te.sample_rate, te.channels, te.codec, te.suffix, te.album_id, te.artist_id, te.album_artist_id, te.cover_art_id, te.missing_at, te.created_at, te.updated_at, te.title, te.track_no, te.disc_no, te.year, te.artist_name, te.album_name, te.album_artist_name,
       (SELECT COALESCE(array_agg(g.name ORDER BY g.name), '{}')
        FROM track_genres tg JOIN genres g ON g.id = tg.genre_id
        WHERE tg.track_id = te.id)::text[] AS genres,
       ts_rank(ts.tsv, websearch_to_tsquery('simple', immutable_unaccent($2::text))) AS rank
FROM track_search ts
JOIN tracks_effective te ON te.id = ts.track_id
WHERE te.missing_at IS NULL
  AND ts.tsv @@ websearch_to_tsquery('simple', immutable_unaccent($2::text))
ORDER BY rank DESC, lower(te.title)
LIMIT $1
`

type SearchTracksExactParams struct {
	Limit int32
	Query string
}

type SearchTracksExactRow struct {
	ID              uuid.UUID
	RootID          uuid.UUID
	RelPath         string
	Size            int64
	Mtime           time.Time
	ContentHash     []byte
	DurationMs      *int32
	Bitrate         *int32
	SampleRate      *int32
	Channels        *int16
	Codec           *string
	Suffix          string
	AlbumID         pgtype.UUID
	ArtistID        pgtype.UUID
	AlbumArtistID   pgtype.UUID
	CoverArtID      pgtype.UUID
	MissingAt       pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Title           string
	TrackNo         *int32
	DiscNo          *int32
	Year            *int32
	ArtistName      string
	AlbumName       string
	AlbumArtistName string
	Genres          []string
	Rank            float32
}

// ---- search -------------------------------------------------------------------
// Ranked full-text search. websearch_to_tsquery accepts what a person actually
// types — bare words, quoted phrases, "or" — without erroring on punctuation
// the way to_tsquery does.
func (q *Queries) SearchTracksExact(ctx context.Context, arg SearchTracksExactParams) ([]SearchTracksExactRow, error) {
	rows, err := q.db.Query(ctx, searchTracksExact, arg.Limit, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTracksExactRow{}
	for rows.Next() {
		var i SearchTracksExactRow
		if err := rows.Scan(
			&i.ID,
			&i.RootID,
			&i.RelPath,
			&i.Size,
			&i.Mtime,
			&i.ContentHash,
			&i.DurationMs,
			&i.Bitrate,
			&i.SampleRate,
			&i.Channels,
			&i.Codec,
			&i.Suffix,
			&i.AlbumID,
			&i.ArtistID,
			&i.AlbumArtistID,
			&i.CoverArtID,
			&i.MissingAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.TrackNo,
			&i.DiscNo,
			&i.Year,
			&i.ArtistName,
			&i.AlbumName,
			&i.AlbumArtistName,
			&i.Genres,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTracksFuzzy = `-- name: SearchTracksFuzzy :many
SELECT te.id, te.root_id, te.rel_path, te.size, te.mtime, te.content_hash, te.duration_ms, te.bitrate, te.sample_rate, te.channels, te.codec, te.suffix, te.album_id, te.artist_id, te.album_artist_id, te.cover_art_id, te.missing_at, te.created_at, te.updated_at, te.title, te.track_no, te.disc_no, te.year, te.artist_name, te.album_name, te.album_artist_name,
       (SELECT COALESCE(array_agg(g.name ORDER BY g.name), '{}')
        FROM track_genres tg JOIN genres g ON g.id = tg.genre_id
        WHERE tg.track_id = te.id)::text[] AS genres,
       word_similarity($2::text, ts.haystack) AS rank
FROM track_search ts
JOIN tracks_effective te ON te.id = ts.track_id
WHERE te.missing_at IS NULL
  AND $2::text <% ts.haystack
ORDER BY rank DESC, lower(te.title)
LIMIT $1
`

type SearchTracksFuzzyParams struct {
	Limit int32
	Query string
}

type SearchTracksFuzzyRow struct {
	ID              uuid.UUID
	RootID          uuid.UUID
	RelPath         string
	Size            int64
	Mtime           time.Time
	ContentHash     []byte
	DurationMs      *int32
	Bitrate         *int32
	SampleRate      *int32
	Channels        *int16
	Codec           *string
	Suffix          string
	AlbumID         pgtype.UUID
	ArtistID        pgtype.UUID
	AlbumArtistID   pgtype.UUID
	CoverArtID      pgtype.UUID
	MissingAt       pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Title           string
	TrackNo         *int32
	DiscNo          *int32
	Year            *int32
	ArtistName      string
	AlbumName       string
	AlbumArtistName string
	Genres          []string
	Rank            float32
}

// Trigram fallback, for when exact matching finds too little: typos
// ("radiohed"), partial words, and missing diacritics. Deliberately a separate
// query rather than an OR — combining them would stop Postgres using either
// index and turn every search into a sequential scan.
//
// word_similarity, not similarity: the latter compares whole strings, so a
// short query against a long haystack ("Airbag Radiohead OK Computer
// Alternative Rock") scores far below any usable threshold and matches
// nothing. The <% operator asks instead whether the query closely matches some
// run of words *inside* the haystack, which is what a search box means.
func (q *Queries) SearchTracksFuzzy(ctx context.Context, arg SearchTracksFuzzyParams) ([]SearchTracksFuzzyRow, error) {
	rows, err := q.db.Query(ctx, searchTracksFuzzy, arg.Limit, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTracksFuzzyRow{}
	for rows.Next() {
		var i SearchTracksFuzzyRow
		if err := rows.Scan(
			&i.ID,
			&i.RootID,
			&i.RelPath,
			&i.Size,
			&i.Mtime,
			&i.ContentHash,
			&i.DurationMs,
			&i.Bitrate,
			&i.SampleRate,
			&i.Channels,
			&i.Codec,
			&i.Suffix,
			&i.AlbumID,
			&i.ArtistID,
			&i.AlbumArtistID,
			&i.CoverArtID,
			&i.MissingAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.TrackNo,
			&i.DiscNo,
			&i.Year,
			&i.ArtistName,
			&i.AlbumName,
			&i.AlbumArtistName,
			&i.Genres,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTrackOverride = `-- name: UpsertTrackOverride :one

INSERT INTO track_overrides (track_id, title, artist_name, album_name,
                             album_artist_name, genre, year, track_no, disc_no)
VALUES ($1, $2::text, $3::text,
        $4::text, $5::text,
        $6::text, $7::int,
        $8::int, $9::int)
ON CONFLICT (track_id) DO UPDATE SET
    title             = COALESCE(EXCLUDED.title, track_overrides.title),
    artist_name       = COALESCE(EXCLUDED.artist_name, track_overrides.artist_name),
    album_name        = COALESCE(EXCLUDED.album_name, track_overrides.album_name),
    album_artist_name = COALESCE(EXCLUDED.album_artist_name, track_overrides.album_artist_name),
    genre             = COALESCE(EXCLUDED.genre, track_overrides.genre),
    year              = COALESCE(EXCLUDED.year, track_overrides.year),
    track_no          = COALESCE(EXCLUDED.track_no, track_overrides.track_no),
    disc_no           = COALESCE(EXCLUDED.disc_no, track_overrides.disc_no),
    updated_at        = now()
RETURNING track_id, title, artist_name, album_name, album_artist_name, genre, year, track_no, disc_no, updated_at
`

type UpsertTrackOverrideParams struct {
	TrackID         uuid.UUID
	Title           *string
	ArtistName      *string
	AlbumName       *string
	AlbumArtistName *string
	Genre           *string
	Year            *int32
	TrackNo         *int32
	DiscNo          *int32
}

// ---- overrides ----------------------------------------------------------------
func (q *Queries) UpsertTrackOverride(ctx context.Context, arg UpsertTrackOverrideParams) (TrackOverride, error) {
	row := q.db.QueryRow(ctx, upsertTrackOverride,
		arg.TrackID,
		arg.Title,
		arg.ArtistName,
		arg.AlbumName,
		arg.AlbumArtistName,
		arg.Genre,
		arg.Year,
		arg.TrackNo,
		arg.DiscNo,
	)
	var i TrackOverride
	err := row.Scan(
		&i.TrackID,
		&i.Title,
		&i.ArtistName,
		&i.AlbumName,
		&i.AlbumArtistName,
		&i.Genre,
		&i.Year,
		&i.TrackNo,
		&i.DiscNo,
		&i.UpdatedAt,
	)
	return i, err
}
