// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimJob = `-- name: ClaimJob :one
UPDATE jobs
SET state = 'running', started_at = now(), attempts = attempts + 1
WHERE id = (
    SELECT id FROM jobs
    WHERE state = 'queued' AND run_after <= now()
    ORDER BY priority DESC, run_after
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, type, payload, priority, state, attempts, max_attempts, error, dedupe_key, run_after, created_at, started_at, finished_at
`

// The canonical multi-worker claim. SKIP LOCKED lets every worker drain the
// queue concurrently without contending on the same row or double-claiming.
func (q *Queries) ClaimJob(ctx context.Context) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Priority,
		&i.State,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.DedupeKey,
		&i.RunAfter,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE jobs
SET state = 'done', finished_at = now(), error = NULL, dedupe_key = NULL
WHERE id = $1
`

// Clearing dedupe_key on completion lets the same logical work be enqueued
// again later; leaving it would make the unique index reject every future
// enqueue for that key.
func (q *Queries) CompleteJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, completeJob, id)
	return err
}

const countJobsByState = `-- name: CountJobsByState :many
SELECT state, count(*) AS count FROM jobs GROUP BY state
`

type CountJobsByStateRow struct {
	State JobState
	Count int64
}

func (q *Queries) CountJobsByState(ctx context.Context) ([]CountJobsByStateRow, error) {
	rows, err := q.db.Query(ctx, countJobsByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountJobsByStateRow{}
	for rows.Next() {
		var i CountJobsByStateRow
		if err := rows.Scan(&i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteFinishedJobsBefore = `-- name: DeleteFinishedJobsBefore :execrows
DELETE FROM jobs
WHERE state IN ('done', 'failed') AND finished_at < now() - $1::interval
`

func (q *Queries) DeleteFinishedJobsBefore(ctx context.Context, olderThan pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFinishedJobsBefore, olderThan)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO jobs (type, payload, priority, dedupe_key, run_after, max_attempts)
VALUES ($1, $2, $3, $5::text, now() + $6::interval, $4)
ON CONFLICT (dedupe_key) DO UPDATE
SET run_after = GREATEST(jobs.run_after, EXCLUDED.run_after),
    priority  = GREATEST(jobs.priority, EXCLUDED.priority)
RETURNING id, type, payload, priority, state, attempts, max_attempts, error, dedupe_key, run_after, created_at, started_at, finished_at
`

type EnqueueJobParams struct {
	Type        string
	Payload     []byte
	Priority    int32
	MaxAttempts int32
	DedupeKey   *string
	Delay       pgtype.Interval
}

// Enqueue is idempotent on dedupe_key: a watcher firing several events for one
// file write produces one job. Touching run_after on conflict lets a repeated
// event push the work later, which is what debouncing an active writer wants.
// run_after is computed by the database, never by the caller. A client-supplied
// timestamp makes scheduling depend on the app and database clocks agreeing: a
// host a few milliseconds ahead produces jobs that are not yet claimable when
// the NOTIFY arrives, so every one of them waits for the next poll instead.
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.Type,
		arg.Payload,
		arg.Priority,
		arg.MaxAttempts,
		arg.DedupeKey,
		arg.Delay,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Priority,
		&i.State,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.DedupeKey,
		&i.RunAfter,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, type, payload, priority, state, attempts, max_attempts, error, dedupe_key, run_after, created_at, started_at, finished_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Priority,
		&i.State,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.DedupeKey,
		&i.RunAfter,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, type, payload, priority, state, attempts, max_attempts, error, dedupe_key, run_after, created_at, started_at, finished_at FROM jobs
WHERE ($2::job_state IS NULL OR state = $2::job_state)
ORDER BY created_at DESC
LIMIT $1
`

type ListJobsParams struct {
	Limit int32
	State *JobState
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Limit, arg.State)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Payload,
			&i.Priority,
			&i.State,
			&i.Attempts,
			&i.MaxAttempts,
			&i.Error,
			&i.DedupeKey,
			&i.RunAfter,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueStaleJobs = `-- name: RequeueStaleJobs :execrows
UPDATE jobs
SET state = 'queued', started_at = NULL
WHERE state = 'running' AND started_at < now() - $1::interval
`

// Requeues jobs left 'running' by a process that died. Without this a crash
// during a scan strands the work forever, since nothing else revisits a row
// that was already claimed.
func (q *Queries) RequeueStaleJobs(ctx context.Context, staleAfter pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, requeueStaleJobs, staleAfter)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryOrFailJob = `-- name: RetryOrFailJob :one
UPDATE jobs
SET state = CASE WHEN attempts >= max_attempts THEN 'failed'::job_state
                 ELSE 'queued'::job_state END,
    error = $1::text,
    run_after = CASE WHEN attempts >= max_attempts THEN run_after
                     ELSE now() + $2::interval END,
    finished_at = CASE WHEN attempts >= max_attempts THEN now() ELSE NULL END,
    dedupe_key = CASE WHEN attempts >= max_attempts THEN NULL ELSE dedupe_key END
WHERE id = $3
RETURNING id, type, payload, priority, state, attempts, max_attempts, error, dedupe_key, run_after, created_at, started_at, finished_at
`

type RetryOrFailJobParams struct {
	Error   string
	Backoff pgtype.Interval
	ID      uuid.UUID
}

// A job below its attempt ceiling goes back to 'queued' with a backoff;
// otherwise it is terminal.
func (q *Queries) RetryOrFailJob(ctx context.Context, arg RetryOrFailJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, retryOrFailJob, arg.Error, arg.Backoff, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Priority,
		&i.State,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.DedupeKey,
		&i.RunAfter,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
