// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: library.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTracks = `-- name: CountTracks :one

SELECT count(*) FROM tracks WHERE missing_at IS NULL
`

// ---- counts -----------------------------------------------------------------
func (q *Queries) CountTracks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTracks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMissingTracksOlderThan = `-- name: DeleteMissingTracksOlderThan :execrows
DELETE FROM tracks
WHERE missing_at IS NOT NULL AND missing_at < now() - $1::interval
`

// Cutoff computed server-side, for the same reason run_after is: the database
// clock is the only one that matters here.
func (q *Queries) DeleteMissingTracksOlderThan(ctx context.Context, olderThan pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMissingTracksOlderThan, olderThan)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOrphanedAlbums = `-- name: DeleteOrphanedAlbums :execrows
DELETE FROM albums
WHERE NOT EXISTS (SELECT 1 FROM tracks WHERE tracks.album_id = albums.id)
`

// Albums and artists are swept in two statements, deliberately. A single
// statement with a CTE cannot work: every part of it sees the same snapshot, so
// the artist check would still see the albums the CTE is deleting and spare
// every artist whose only album just went away.
func (q *Queries) DeleteOrphanedAlbums(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrphanedAlbums)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOrphanedArtists = `-- name: DeleteOrphanedArtists :execrows
DELETE FROM artists
WHERE NOT EXISTS (SELECT 1 FROM tracks WHERE tracks.artist_id = artists.id)
  AND NOT EXISTS (SELECT 1 FROM tracks WHERE tracks.album_artist_id = artists.id)
  AND NOT EXISTS (SELECT 1 FROM albums WHERE albums.album_artist_id = artists.id)
`

func (q *Queries) DeleteOrphanedArtists(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrphanedArtists)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOrphanedCoverArt = `-- name: DeleteOrphanedCoverArt :many
DELETE FROM cover_art
WHERE NOT EXISTS (SELECT 1 FROM tracks WHERE tracks.cover_art_id = cover_art.id)
  AND NOT EXISTS (SELECT 1 FROM albums WHERE albums.cover_art_id = cover_art.id)
RETURNING blob_key
`

// Rows that no track references any more. Cover art is content-addressed and
// shared, so it can only be removed once nothing points at it.
func (q *Queries) DeleteOrphanedCoverArt(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteOrphanedCoverArt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blob_key string
		if err := rows.Scan(&blob_key); err != nil {
			return nil, err
		}
		items = append(items, blob_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTrackByHash = `-- name: FindTrackByHash :one
SELECT id, root_id, rel_path, size, mtime, content_hash, duration_ms, bitrate, sample_rate, channels, codec, suffix, title, track_no, disc_no, year, album_id, artist_id, album_artist_id, cover_art_id, missing_at, created_at, updated_at FROM tracks
WHERE content_hash = $1 AND root_id = $2
ORDER BY missing_at NULLS LAST
LIMIT 1
`

type FindTrackByHashParams struct {
	ContentHash []byte
	RootID      uuid.UUID
}

// Move detection: a file whose content hash matches a row that is now missing,
// or whose recorded path no longer exists, is the same track relocated.
func (q *Queries) FindTrackByHash(ctx context.Context, arg FindTrackByHashParams) (Track, error) {
	row := q.db.QueryRow(ctx, findTrackByHash, arg.ContentHash, arg.RootID)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.RootID,
		&i.RelPath,
		&i.Size,
		&i.Mtime,
		&i.ContentHash,
		&i.DurationMs,
		&i.Bitrate,
		&i.SampleRate,
		&i.Channels,
		&i.Codec,
		&i.Suffix,
		&i.Title,
		&i.TrackNo,
		&i.DiscNo,
		&i.Year,
		&i.AlbumID,
		&i.ArtistID,
		&i.AlbumArtistID,
		&i.CoverArtID,
		&i.MissingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLibraryRoot = `-- name: GetLibraryRoot :one
SELECT id, path, writable, enabled, last_scan_started_at, last_scan_finished_at, last_scan_error, created_at FROM library_roots WHERE id = $1
`

func (q *Queries) GetLibraryRoot(ctx context.Context, id uuid.UUID) (LibraryRoot, error) {
	row := q.db.QueryRow(ctx, getLibraryRoot, id)
	var i LibraryRoot
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Writable,
		&i.Enabled,
		&i.LastScanStartedAt,
		&i.LastScanFinishedAt,
		&i.LastScanError,
		&i.CreatedAt,
	)
	return i, err
}

const getTrackByPath = `-- name: GetTrackByPath :one
SELECT id, root_id, rel_path, size, mtime, content_hash, duration_ms, bitrate, sample_rate, channels, codec, suffix, title, track_no, disc_no, year, album_id, artist_id, album_artist_id, cover_art_id, missing_at, created_at, updated_at FROM tracks WHERE root_id = $1 AND rel_path = $2
`

type GetTrackByPathParams struct {
	RootID  uuid.UUID
	RelPath string
}

func (q *Queries) GetTrackByPath(ctx context.Context, arg GetTrackByPathParams) (Track, error) {
	row := q.db.QueryRow(ctx, getTrackByPath, arg.RootID, arg.RelPath)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.RootID,
		&i.RelPath,
		&i.Size,
		&i.Mtime,
		&i.ContentHash,
		&i.DurationMs,
		&i.Bitrate,
		&i.SampleRate,
		&i.Channels,
		&i.Codec,
		&i.Suffix,
		&i.Title,
		&i.TrackNo,
		&i.DiscNo,
		&i.Year,
		&i.AlbumID,
		&i.ArtistID,
		&i.AlbumArtistID,
		&i.CoverArtID,
		&i.MissingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const libraryStats = `-- name: LibraryStats :one
SELECT
    (SELECT count(*) FROM tracks WHERE missing_at IS NULL)  AS tracks,
    (SELECT count(*) FROM tracks WHERE missing_at IS NOT NULL) AS missing,
    (SELECT count(*) FROM albums)                            AS albums,
    (SELECT count(*) FROM artists)                           AS artists,
    (SELECT count(*) FROM genres)                            AS genres,
    (SELECT COALESCE(sum(duration_ms), 0) FROM tracks WHERE missing_at IS NULL) AS total_duration_ms
`

type LibraryStatsRow struct {
	Tracks          int64
	Missing         int64
	Albums          int64
	Artists         int64
	Genres          int64
	TotalDurationMs interface{}
}

func (q *Queries) LibraryStats(ctx context.Context) (LibraryStatsRow, error) {
	row := q.db.QueryRow(ctx, libraryStats)
	var i LibraryStatsRow
	err := row.Scan(
		&i.Tracks,
		&i.Missing,
		&i.Albums,
		&i.Artists,
		&i.Genres,
		&i.TotalDurationMs,
	)
	return i, err
}

const listLibraryRoots = `-- name: ListLibraryRoots :many
SELECT id, path, writable, enabled, last_scan_started_at, last_scan_finished_at, last_scan_error, created_at FROM library_roots WHERE enabled ORDER BY path
`

func (q *Queries) ListLibraryRoots(ctx context.Context) ([]LibraryRoot, error) {
	rows, err := q.db.Query(ctx, listLibraryRoots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibraryRoot{}
	for rows.Next() {
		var i LibraryRoot
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Writable,
			&i.Enabled,
			&i.LastScanStartedAt,
			&i.LastScanFinishedAt,
			&i.LastScanError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackStatsForRoot = `-- name: ListTrackStatsForRoot :many

SELECT id, rel_path, size, mtime FROM tracks WHERE root_id = $1
`

type ListTrackStatsForRootRow struct {
	ID      uuid.UUID
	RelPath string
	Size    int64
	Mtime   time.Time
}

// ---- tracks -----------------------------------------------------------------
// Returns just enough to decide whether a file changed, without loading whole
// rows for a library that is mostly unchanged.
func (q *Queries) ListTrackStatsForRoot(ctx context.Context, rootID uuid.UUID) ([]ListTrackStatsForRootRow, error) {
	rows, err := q.db.Query(ctx, listTrackStatsForRoot, rootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrackStatsForRootRow{}
	for rows.Next() {
		var i ListTrackStatsForRootRow
		if err := rows.Scan(
			&i.ID,
			&i.RelPath,
			&i.Size,
			&i.Mtime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScanFinished = `-- name: MarkScanFinished :exec
UPDATE library_roots
SET last_scan_finished_at = now(), last_scan_error = $2::text
WHERE id = $1
`

type MarkScanFinishedParams struct {
	ID    uuid.UUID
	Error *string
}

func (q *Queries) MarkScanFinished(ctx context.Context, arg MarkScanFinishedParams) error {
	_, err := q.db.Exec(ctx, markScanFinished, arg.ID, arg.Error)
	return err
}

const markScanStarted = `-- name: MarkScanStarted :exec
UPDATE library_roots
SET last_scan_started_at = now(), last_scan_error = NULL
WHERE id = $1
`

func (q *Queries) MarkScanStarted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markScanStarted, id)
	return err
}

const markTracksMissing = `-- name: MarkTracksMissing :execrows
UPDATE tracks SET missing_at = now(), updated_at = now()
WHERE id = ANY($1::uuid[]) AND missing_at IS NULL
`

func (q *Queries) MarkTracksMissing(ctx context.Context, ids []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markTracksMissing, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveTrack = `-- name: MoveTrack :one
UPDATE tracks
SET rel_path = $1::text,
    size = $2::bigint,
    mtime = $3::timestamptz,
    missing_at = NULL,
    updated_at = now()
WHERE id = $4
RETURNING id, root_id, rel_path, size, mtime, content_hash, duration_ms, bitrate, sample_rate, channels, codec, suffix, title, track_no, disc_no, year, album_id, artist_id, album_artist_id, cover_art_id, missing_at, created_at, updated_at
`

type MoveTrackParams struct {
	RelPath string
	Size    int64
	Mtime   time.Time
	ID      uuid.UUID
}

// Relocating a track keeps its id, and therefore its playlist entries and play
// history, across a library reorganisation.
func (q *Queries) MoveTrack(ctx context.Context, arg MoveTrackParams) (Track, error) {
	row := q.db.QueryRow(ctx, moveTrack,
		arg.RelPath,
		arg.Size,
		arg.Mtime,
		arg.ID,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.RootID,
		&i.RelPath,
		&i.Size,
		&i.Mtime,
		&i.ContentHash,
		&i.DurationMs,
		&i.Bitrate,
		&i.SampleRate,
		&i.Channels,
		&i.Codec,
		&i.Suffix,
		&i.Title,
		&i.TrackNo,
		&i.DiscNo,
		&i.Year,
		&i.AlbumID,
		&i.ArtistID,
		&i.AlbumArtistID,
		&i.CoverArtID,
		&i.MissingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const replaceTrackGenres = `-- name: ReplaceTrackGenres :exec
WITH cleared AS (
    DELETE FROM track_genres WHERE track_id = $1
)
INSERT INTO track_genres (track_id, genre_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type ReplaceTrackGenresParams struct {
	TrackID  uuid.UUID
	GenreIds []uuid.UUID
}

func (q *Queries) ReplaceTrackGenres(ctx context.Context, arg ReplaceTrackGenresParams) error {
	_, err := q.db.Exec(ctx, replaceTrackGenres, arg.TrackID, arg.GenreIds)
	return err
}

const upsertAlbum = `-- name: UpsertAlbum :one
INSERT INTO albums (name, norm_name, album_artist_id, year, cover_art_id)
VALUES ($1, $2, $3::uuid, $4::int, $5::uuid)
ON CONFLICT (norm_name, album_artist_id) DO UPDATE
SET year         = COALESCE(albums.year, EXCLUDED.year),
    cover_art_id = COALESCE(albums.cover_art_id, EXCLUDED.cover_art_id)
RETURNING id, name, norm_name, album_artist_id, year, cover_art_id, disc_count, created_at
`

type UpsertAlbumParams struct {
	Name          string
	NormName      string
	AlbumArtistID pgtype.UUID
	Year          *int32
	CoverArtID    pgtype.UUID
}

func (q *Queries) UpsertAlbum(ctx context.Context, arg UpsertAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, upsertAlbum,
		arg.Name,
		arg.NormName,
		arg.AlbumArtistID,
		arg.Year,
		arg.CoverArtID,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormName,
		&i.AlbumArtistID,
		&i.Year,
		&i.CoverArtID,
		&i.DiscCount,
		&i.CreatedAt,
	)
	return i, err
}

const upsertArtist = `-- name: UpsertArtist :one


INSERT INTO artists (name, norm_name, sort_name)
VALUES ($1, $2, $3::text)
ON CONFLICT (norm_name) DO UPDATE SET name = artists.name
RETURNING id, name, norm_name, sort_name, mbid, created_at
`

type UpsertArtistParams struct {
	Name     string
	NormName string
	SortName *string
}

// ---- reconciliation ---------------------------------------------------------
// Reconciliation is by normalised name, so "The Beatles" and "Beatles" collapse
// to one artist. ON CONFLICT DO UPDATE rather than DO NOTHING because a bare
// DO NOTHING returns no row on conflict, which would cost a second round trip
// on the overwhelmingly common already-exists path.
func (q *Queries) UpsertArtist(ctx context.Context, arg UpsertArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, upsertArtist, arg.Name, arg.NormName, arg.SortName)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormName,
		&i.SortName,
		&i.Mbid,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCoverArt = `-- name: UpsertCoverArt :one
INSERT INTO cover_art (hash, blob_key, source, mime, width, height, bytes)
VALUES ($1, $2, $3, $4, $6::int, $7::int, $5)
ON CONFLICT (hash) DO UPDATE SET blob_key = cover_art.blob_key
RETURNING id, hash, blob_key, source, mime, width, height, bytes, created_at
`

type UpsertCoverArtParams struct {
	Hash    []byte
	BlobKey string
	Source  string
	Mime    string
	Bytes   int64
	Width   *int32
	Height  *int32
}

func (q *Queries) UpsertCoverArt(ctx context.Context, arg UpsertCoverArtParams) (CoverArt, error) {
	row := q.db.QueryRow(ctx, upsertCoverArt,
		arg.Hash,
		arg.BlobKey,
		arg.Source,
		arg.Mime,
		arg.Bytes,
		arg.Width,
		arg.Height,
	)
	var i CoverArt
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.BlobKey,
		&i.Source,
		&i.Mime,
		&i.Width,
		&i.Height,
		&i.Bytes,
		&i.CreatedAt,
	)
	return i, err
}

const upsertGenre = `-- name: UpsertGenre :one
INSERT INTO genres (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = genres.name
RETURNING id, name
`

func (q *Queries) UpsertGenre(ctx context.Context, name string) (Genre, error) {
	row := q.db.QueryRow(ctx, upsertGenre, name)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const upsertLibraryRoot = `-- name: UpsertLibraryRoot :one

INSERT INTO library_roots (path, writable)
VALUES ($1, $2)
ON CONFLICT (path) DO UPDATE SET writable = EXCLUDED.writable
RETURNING id, path, writable, enabled, last_scan_started_at, last_scan_finished_at, last_scan_error, created_at
`

type UpsertLibraryRootParams struct {
	Path     string
	Writable bool
}

// ---- roots -----------------------------------------------------------------
func (q *Queries) UpsertLibraryRoot(ctx context.Context, arg UpsertLibraryRootParams) (LibraryRoot, error) {
	row := q.db.QueryRow(ctx, upsertLibraryRoot, arg.Path, arg.Writable)
	var i LibraryRoot
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Writable,
		&i.Enabled,
		&i.LastScanStartedAt,
		&i.LastScanFinishedAt,
		&i.LastScanError,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTrack = `-- name: UpsertTrack :one
INSERT INTO tracks (
    root_id, rel_path, size, mtime, content_hash,
    duration_ms, bitrate, sample_rate, channels, codec, suffix,
    title, track_no, disc_no, year,
    album_id, artist_id, album_artist_id, cover_art_id, missing_at
) VALUES (
    $1, $2, $3, $4, $5,
    $8::int, $9::int, $10::int,
    $11::smallint, $12::text, $6,
    $7, $13::int, $14::int, $15::int,
    $16::uuid, $17::uuid,
    $18::uuid, $19::uuid, NULL
)
ON CONFLICT (root_id, rel_path) DO UPDATE SET
    size = EXCLUDED.size, mtime = EXCLUDED.mtime, content_hash = EXCLUDED.content_hash,
    duration_ms = EXCLUDED.duration_ms, bitrate = EXCLUDED.bitrate,
    sample_rate = EXCLUDED.sample_rate, channels = EXCLUDED.channels,
    codec = EXCLUDED.codec, suffix = EXCLUDED.suffix,
    title = EXCLUDED.title, track_no = EXCLUDED.track_no,
    disc_no = EXCLUDED.disc_no, year = EXCLUDED.year,
    album_id = EXCLUDED.album_id, artist_id = EXCLUDED.artist_id,
    album_artist_id = EXCLUDED.album_artist_id, cover_art_id = EXCLUDED.cover_art_id,
    missing_at = NULL,
    updated_at = now()
RETURNING id, root_id, rel_path, size, mtime, content_hash, duration_ms, bitrate, sample_rate, channels, codec, suffix, title, track_no, disc_no, year, album_id, artist_id, album_artist_id, cover_art_id, missing_at, created_at, updated_at
`

type UpsertTrackParams struct {
	RootID        uuid.UUID
	RelPath       string
	Size          int64
	Mtime         time.Time
	ContentHash   []byte
	Suffix        string
	Title         string
	DurationMs    *int32
	Bitrate       *int32
	SampleRate    *int32
	Channels      *int16
	Codec         *string
	TrackNo       *int32
	DiscNo        *int32
	Year          *int32
	AlbumID       pgtype.UUID
	ArtistID      pgtype.UUID
	AlbumArtistID pgtype.UUID
	CoverArtID    pgtype.UUID
}

func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) (Track, error) {
	row := q.db.QueryRow(ctx, upsertTrack,
		arg.RootID,
		arg.RelPath,
		arg.Size,
		arg.Mtime,
		arg.ContentHash,
		arg.Suffix,
		arg.Title,
		arg.DurationMs,
		arg.Bitrate,
		arg.SampleRate,
		arg.Channels,
		arg.Codec,
		arg.TrackNo,
		arg.DiscNo,
		arg.Year,
		arg.AlbumID,
		arg.ArtistID,
		arg.AlbumArtistID,
		arg.CoverArtID,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.RootID,
		&i.RelPath,
		&i.Size,
		&i.Mtime,
		&i.ContentHash,
		&i.DurationMs,
		&i.Bitrate,
		&i.SampleRate,
		&i.Channels,
		&i.Codec,
		&i.Suffix,
		&i.Title,
		&i.TrackNo,
		&i.DiscNo,
		&i.Year,
		&i.AlbumID,
		&i.ArtistID,
		&i.AlbumArtistID,
		&i.CoverArtID,
		&i.MissingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTrackSearch = `-- name: UpsertTrackSearch :exec
INSERT INTO track_search (track_id, haystack)
VALUES ($1, $2)
ON CONFLICT (track_id) DO UPDATE SET haystack = EXCLUDED.haystack
`

type UpsertTrackSearchParams struct {
	TrackID  uuid.UUID
	Haystack string
}

// Written in the same transaction as the track, from the effective values.
func (q *Queries) UpsertTrackSearch(ctx context.Context, arg UpsertTrackSearchParams) error {
	_, err := q.db.Exec(ctx, upsertTrackSearch, arg.TrackID, arg.Haystack)
	return err
}
