// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAlbumCoverArt = `-- name: GetAlbumCoverArt :one
SELECT ca.id, ca.blob_key, ca.mime, ca.bytes
FROM albums al
JOIN cover_art ca ON ca.id = al.cover_art_id
WHERE al.id = $1
`

type GetAlbumCoverArtRow struct {
	ID      uuid.UUID
	BlobKey string
	Mime    string
	Bytes   int64
}

// Album art is requested by album far more often than by its own id, so this
// saves the client a lookup it would otherwise always have to make first.
func (q *Queries) GetAlbumCoverArt(ctx context.Context, id uuid.UUID) (GetAlbumCoverArtRow, error) {
	row := q.db.QueryRow(ctx, getAlbumCoverArt, id)
	var i GetAlbumCoverArtRow
	err := row.Scan(
		&i.ID,
		&i.BlobKey,
		&i.Mime,
		&i.Bytes,
	)
	return i, err
}

const getCoverArt = `-- name: GetCoverArt :one
SELECT id, blob_key, mime, bytes FROM cover_art WHERE id = $1
`

type GetCoverArtRow struct {
	ID      uuid.UUID
	BlobKey string
	Mime    string
	Bytes   int64
}

func (q *Queries) GetCoverArt(ctx context.Context, id uuid.UUID) (GetCoverArtRow, error) {
	row := q.db.QueryRow(ctx, getCoverArt, id)
	var i GetCoverArtRow
	err := row.Scan(
		&i.ID,
		&i.BlobKey,
		&i.Mime,
		&i.Bytes,
	)
	return i, err
}

const getTrackForStream = `-- name: GetTrackForStream :one
SELECT t.id, t.rel_path, t.suffix, t.size, t.mtime, t.duration_ms, t.codec,
       t.content_hash, r.path AS root_path
FROM tracks t
JOIN library_roots r ON r.id = t.root_id
WHERE t.id = $1 AND t.missing_at IS NULL
`

type GetTrackForStreamRow struct {
	ID          uuid.UUID
	RelPath     string
	Suffix      string
	Size        int64
	Mtime       time.Time
	DurationMs  *int32
	Codec       *string
	ContentHash []byte
	RootPath    string
}

// Everything needed to serve one track's bytes, in a single round trip: the
// root path and relative path that locate the file, plus the metadata the
// response headers need.
func (q *Queries) GetTrackForStream(ctx context.Context, id uuid.UUID) (GetTrackForStreamRow, error) {
	row := q.db.QueryRow(ctx, getTrackForStream, id)
	var i GetTrackForStreamRow
	err := row.Scan(
		&i.ID,
		&i.RelPath,
		&i.Suffix,
		&i.Size,
		&i.Mtime,
		&i.DurationMs,
		&i.Codec,
		&i.ContentHash,
		&i.RootPath,
	)
	return i, err
}
