// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type FavoriteEntity string

const (
	FavoriteEntityTrack  FavoriteEntity = "track"
	FavoriteEntityAlbum  FavoriteEntity = "album"
	FavoriteEntityArtist FavoriteEntity = "artist"
)

func (e *FavoriteEntity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FavoriteEntity(s)
	case string:
		*e = FavoriteEntity(s)
	default:
		return fmt.Errorf("unsupported scan type for FavoriteEntity: %T", src)
	}
	return nil
}

type NullFavoriteEntity struct {
	FavoriteEntity FavoriteEntity
	Valid          bool // Valid is true if FavoriteEntity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFavoriteEntity) Scan(value interface{}) error {
	if value == nil {
		ns.FavoriteEntity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FavoriteEntity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFavoriteEntity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FavoriteEntity), nil
}

type JobState string

const (
	JobStateQueued  JobState = "queued"
	JobStateRunning JobState = "running"
	JobStateDone    JobState = "done"
	JobStateFailed  JobState = "failed"
)

func (e *JobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobState(s)
	case string:
		*e = JobState(s)
	default:
		return fmt.Errorf("unsupported scan type for JobState: %T", src)
	}
	return nil
}

type NullJobState struct {
	JobState JobState
	Valid    bool // Valid is true if JobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobState) Scan(value interface{}) error {
	if value == nil {
		ns.JobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobState), nil
}

type UserRole string

const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type YtState string

const (
	YtStatePending     YtState = "pending"
	YtStateDownloading YtState = "downloading"
	YtStateReady       YtState = "ready"
	YtStateFailed      YtState = "failed"
	YtStateEvicted     YtState = "evicted"
)

func (e *YtState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = YtState(s)
	case string:
		*e = YtState(s)
	default:
		return fmt.Errorf("unsupported scan type for YtState: %T", src)
	}
	return nil
}

type NullYtState struct {
	YtState YtState
	Valid   bool // Valid is true if YtState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullYtState) Scan(value interface{}) error {
	if value == nil {
		ns.YtState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.YtState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullYtState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.YtState), nil
}

type Album struct {
	ID            uuid.UUID
	Name          string
	NormName      string
	AlbumArtistID pgtype.UUID
	Year          *int32
	CoverArtID    pgtype.UUID
	DiscCount     int32
	CreatedAt     time.Time
}

type Artist struct {
	ID        uuid.UUID
	Name      string
	NormName  string
	SortName  *string
	Mbid      pgtype.UUID
	CreatedAt time.Time
}

type CoverArt struct {
	ID        uuid.UUID
	Hash      []byte
	BlobKey   string
	Source    string
	Mime      string
	Width     *int32
	Height    *int32
	Bytes     int64
	CreatedAt time.Time
}

type Favorite struct {
	UserID     uuid.UUID
	EntityType FavoriteEntity
	EntityID   uuid.UUID
	CreatedAt  time.Time
}

type Genre struct {
	ID   uuid.UUID
	Name string
}

type Job struct {
	ID          uuid.UUID
	Type        string
	Payload     []byte
	Priority    int32
	State       JobState
	Attempts    int32
	MaxAttempts int32
	Error       *string
	DedupeKey   *string
	RunAfter    time.Time
	CreatedAt   time.Time
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
}

type LibraryRoot struct {
	ID                 uuid.UUID
	Path               string
	Writable           bool
	Enabled            bool
	LastScanStartedAt  pgtype.Timestamptz
	LastScanFinishedAt pgtype.Timestamptz
	LastScanError      *string
	CreatedAt          time.Time
}

type Play struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	TrackID  pgtype.UUID
	PlayedAt time.Time
	MsPlayed int32
	Source   string
}

type Playlist struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description string
	Public      bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PlaylistTrack struct {
	ID         uuid.UUID
	PlaylistID uuid.UUID
	TrackID    uuid.UUID
	Position   int32
	AddedAt    time.Time
}

type Session struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	CsrfToken  string
	UserAgent  *string
	Ip         *netip.Addr
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
}

type Track struct {
	ID            uuid.UUID
	RootID        uuid.UUID
	RelPath       string
	Size          int64
	Mtime         time.Time
	ContentHash   []byte
	DurationMs    *int32
	Bitrate       *int32
	SampleRate    *int32
	Channels      *int16
	Codec         *string
	Suffix        string
	Title         string
	TrackNo       *int32
	DiscNo        *int32
	Year          *int32
	AlbumID       pgtype.UUID
	ArtistID      pgtype.UUID
	AlbumArtistID pgtype.UUID
	CoverArtID    pgtype.UUID
	MissingAt     pgtype.Timestamptz
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type TrackGenre struct {
	TrackID uuid.UUID
	GenreID uuid.UUID
}

type TrackOverride struct {
	TrackID         uuid.UUID
	Title           *string
	ArtistName      *string
	AlbumName       *string
	AlbumArtistName *string
	Genre           *string
	Year            *int32
	TrackNo         *int32
	DiscNo          *int32
	UpdatedAt       time.Time
}

type TrackSearch struct {
	TrackID  uuid.UUID
	Haystack string
	Tsv      interface{}
}

type TracksEffective struct {
	ID              uuid.UUID
	RootID          uuid.UUID
	RelPath         string
	Size            int64
	Mtime           time.Time
	ContentHash     []byte
	DurationMs      *int32
	Bitrate         *int32
	SampleRate      *int32
	Channels        *int16
	Codec           *string
	Suffix          string
	AlbumID         pgtype.UUID
	ArtistID        pgtype.UUID
	AlbumArtistID   pgtype.UUID
	CoverArtID      pgtype.UUID
	MissingAt       pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Title           string
	TrackNo         *int32
	DiscNo          *int32
	Year            *int32
	ArtistName      string
	AlbumName       string
	AlbumArtistName string
}

type User struct {
	ID           uuid.UUID
	Email        string
	DisplayName  string
	AvatarUrl    *string
	GoogleSub    *string
	OidcSub      *string
	PasswordHash *string
	Role         UserRole
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DisabledAt   pgtype.Timestamptz
}

type YtItem struct {
	ID              uuid.UUID
	VideoID         string
	Title           string
	Uploader        string
	DurationMs      *int32
	ThumbnailUrl    *string
	State           YtState
	Error           *string
	BlobKey         *string
	Bytes           *int64
	CachedAt        pgtype.Timestamptz
	LastAccessedAt  pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	PromotedTrackID pgtype.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
