// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlists.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :exec

INSERT INTO favorites (user_id, entity_type, entity_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddFavoriteParams struct {
	UserID     uuid.UUID
	EntityType FavoriteEntity
	EntityID   uuid.UUID
}

// ---- favorites ------------------------------------------------------------------
func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.EntityType, arg.EntityID)
	return err
}

const appendPlaylistTrack = `-- name: AppendPlaylistTrack :one
INSERT INTO playlist_tracks (playlist_id, track_id, position)
SELECT $1, $2,
       COALESCE(max(existing.position), -1) + 1
FROM playlist_tracks existing
WHERE existing.playlist_id = $1
RETURNING id, playlist_id, track_id, position, added_at
`

type AppendPlaylistTrackParams struct {
	PlaylistID uuid.UUID
	TrackID    uuid.UUID
}

// Appends at the end. The position is computed in the same statement so two
// concurrent adds cannot both read the same max and collide.
func (q *Queries) AppendPlaylistTrack(ctx context.Context, arg AppendPlaylistTrackParams) (PlaylistTrack, error) {
	row := q.db.QueryRow(ctx, appendPlaylistTrack, arg.PlaylistID, arg.TrackID)
	var i PlaylistTrack
	err := row.Scan(
		&i.ID,
		&i.PlaylistID,
		&i.TrackID,
		&i.Position,
		&i.AddedAt,
	)
	return i, err
}

const compactPlaylistPositions = `-- name: CompactPlaylistPositions :exec
WITH ordered AS (
    SELECT src.id,
           row_number() OVER (ORDER BY src.position, src.id) - 1 AS new_position
    FROM playlist_tracks src WHERE src.playlist_id = $1
)
UPDATE playlist_tracks pt
SET position = ordered.new_position
FROM ordered
WHERE pt.id = ordered.id AND pt.position <> ordered.new_position
`

// Renumbers from zero after a removal, so positions stay dense and the next
// append lands where it should.
func (q *Queries) CompactPlaylistPositions(ctx context.Context, playlistID uuid.UUID) error {
	_, err := q.db.Exec(ctx, compactPlaylistPositions, playlistID)
	return err
}

const countPlaylistTracks = `-- name: CountPlaylistTracks :one
SELECT count(*) FROM playlist_tracks WHERE playlist_id = $1
`

func (q *Queries) CountPlaylistTracks(ctx context.Context, playlistID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPlaylistTracks, playlistID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlaylist = `-- name: CreatePlaylist :one

INSERT INTO playlists (user_id, name, description, public)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, description, public, created_at, updated_at
`

type CreatePlaylistParams struct {
	UserID      uuid.UUID
	Name        string
	Description string
	Public      bool
}

// ---- playlists ----------------------------------------------------------------
func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error) {
	row := q.db.QueryRow(ctx, createPlaylist,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Public,
	)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlaylist = `-- name: DeletePlaylist :execrows
DELETE FROM playlists WHERE id = $1 AND user_id = $2
`

type DeletePlaylistParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeletePlaylist(ctx context.Context, arg DeletePlaylistParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlaylist, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPlaylist = `-- name: GetPlaylist :one
SELECT p.id, p.user_id, p.name, p.description, p.public, p.created_at, p.updated_at,
       (p.user_id = $1) AS owned,
       u.display_name AS owner_name,
       count(pt.id)::bigint AS track_count,
       COALESCE(sum(t.duration_ms), 0)::bigint AS duration_ms
FROM playlists p
JOIN users u ON u.id = p.user_id
LEFT JOIN playlist_tracks pt ON pt.playlist_id = p.id
LEFT JOIN tracks t ON t.id = pt.track_id AND t.missing_at IS NULL
WHERE p.id = $2 AND (p.user_id = $1 OR p.public)
GROUP BY p.id, u.display_name
`

type GetPlaylistParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type GetPlaylistRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description string
	Public      bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Owned       bool
	OwnerName   string
	TrackCount  int64
	DurationMs  int64
}

func (q *Queries) GetPlaylist(ctx context.Context, arg GetPlaylistParams) (GetPlaylistRow, error) {
	row := q.db.QueryRow(ctx, getPlaylist, arg.UserID, arg.ID)
	var i GetPlaylistRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Owned,
		&i.OwnerName,
		&i.TrackCount,
		&i.DurationMs,
	)
	return i, err
}

const getTrackDuration = `-- name: GetTrackDuration :one
SELECT duration_ms FROM tracks WHERE id = $1 AND missing_at IS NULL
`

// Duration is needed server-side to decide whether a reported play qualifies;
// trusting the client's number would let anyone inflate their own counts.
func (q *Queries) GetTrackDuration(ctx context.Context, id uuid.UUID) (*int32, error) {
	row := q.db.QueryRow(ctx, getTrackDuration, id)
	var duration_ms *int32
	err := row.Scan(&duration_ms)
	return duration_ms, err
}

const isFavorite = `-- name: IsFavorite :one
SELECT EXISTS (
    SELECT 1 FROM favorites
    WHERE user_id = $1 AND entity_type = $2 AND entity_id = $3
)
`

type IsFavoriteParams struct {
	UserID     uuid.UUID
	EntityType FavoriteEntity
	EntityID   uuid.UUID
}

func (q *Queries) IsFavorite(ctx context.Context, arg IsFavoriteParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFavorite, arg.UserID, arg.EntityType, arg.EntityID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFavoriteTracks = `-- name: ListFavoriteTracks :many
SELECT te.id, te.root_id, te.rel_path, te.size, te.mtime, te.content_hash, te.duration_ms, te.bitrate, te.sample_rate, te.channels, te.codec, te.suffix, te.album_id, te.artist_id, te.album_artist_id, te.cover_art_id, te.missing_at, te.created_at, te.updated_at, te.title, te.track_no, te.disc_no, te.year, te.artist_name, te.album_name, te.album_artist_name,
       (SELECT COALESCE(array_agg(g.name ORDER BY g.name), '{}')
        FROM track_genres tg JOIN genres g ON g.id = tg.genre_id
        WHERE tg.track_id = te.id)::text[] AS genres,
       f.created_at AS favorited_at
FROM favorites f
JOIN tracks_effective te ON te.id = f.entity_id
WHERE f.user_id = $1 AND f.entity_type = 'track' AND te.missing_at IS NULL
ORDER BY f.created_at DESC
LIMIT $2
`

type ListFavoriteTracksParams struct {
	UserID uuid.UUID
	Limit  int32
}

type ListFavoriteTracksRow struct {
	ID              uuid.UUID
	RootID          uuid.UUID
	RelPath         string
	Size            int64
	Mtime           time.Time
	ContentHash     []byte
	DurationMs      *int32
	Bitrate         *int32
	SampleRate      *int32
	Channels        *int16
	Codec           *string
	Suffix          string
	AlbumID         pgtype.UUID
	ArtistID        pgtype.UUID
	AlbumArtistID   pgtype.UUID
	CoverArtID      pgtype.UUID
	MissingAt       pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Title           string
	TrackNo         *int32
	DiscNo          *int32
	Year            *int32
	ArtistName      string
	AlbumName       string
	AlbumArtistName string
	Genres          []string
	FavoritedAt     time.Time
}

func (q *Queries) ListFavoriteTracks(ctx context.Context, arg ListFavoriteTracksParams) ([]ListFavoriteTracksRow, error) {
	rows, err := q.db.Query(ctx, listFavoriteTracks, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFavoriteTracksRow{}
	for rows.Next() {
		var i ListFavoriteTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.RootID,
			&i.RelPath,
			&i.Size,
			&i.Mtime,
			&i.ContentHash,
			&i.DurationMs,
			&i.Bitrate,
			&i.SampleRate,
			&i.Channels,
			&i.Codec,
			&i.Suffix,
			&i.AlbumID,
			&i.ArtistID,
			&i.AlbumArtistID,
			&i.CoverArtID,
			&i.MissingAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.TrackNo,
			&i.DiscNo,
			&i.Year,
			&i.ArtistName,
			&i.AlbumName,
			&i.AlbumArtistName,
			&i.Genres,
			&i.FavoritedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistory = `-- name: ListHistory :many
SELECT p.id, p.played_at, p.ms_played, p.source,
       te.id AS track_id, te.title, te.artist_name, te.album_name,
       te.album_id, te.cover_art_id, te.duration_ms
FROM plays p
LEFT JOIN tracks_effective te ON te.id = p.track_id
WHERE p.user_id = $1
ORDER BY p.played_at DESC
LIMIT $2
`

type ListHistoryParams struct {
	UserID uuid.UUID
	Limit  int32
}

type ListHistoryRow struct {
	ID         uuid.UUID
	PlayedAt   time.Time
	MsPlayed   int32
	Source     string
	TrackID    pgtype.UUID
	Title      *string
	ArtistName *string
	AlbumName  *string
	AlbumID    pgtype.UUID
	CoverArtID pgtype.UUID
	DurationMs *int32
}

func (q *Queries) ListHistory(ctx context.Context, arg ListHistoryParams) ([]ListHistoryRow, error) {
	rows, err := q.db.Query(ctx, listHistory, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHistoryRow{}
	for rows.Next() {
		var i ListHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayedAt,
			&i.MsPlayed,
			&i.Source,
			&i.TrackID,
			&i.Title,
			&i.ArtistName,
			&i.AlbumName,
			&i.AlbumID,
			&i.CoverArtID,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistTracks = `-- name: ListPlaylistTracks :many

SELECT pt.id AS entry_id, pt.position, pt.added_at,
       te.id, te.root_id, te.rel_path, te.size, te.mtime, te.content_hash, te.duration_ms, te.bitrate, te.sample_rate, te.channels, te.codec, te.suffix, te.album_id, te.artist_id, te.album_artist_id, te.cover_art_id, te.missing_at, te.created_at, te.updated_at, te.title, te.track_no, te.disc_no, te.year, te.artist_name, te.album_name, te.album_artist_name,
       (te.missing_at IS NOT NULL)::bool AS unavailable,
       (SELECT COALESCE(array_agg(g.name ORDER BY g.name), '{}')
        FROM track_genres tg JOIN genres g ON g.id = tg.genre_id
        WHERE tg.track_id = te.id)::text[] AS genres,
       EXISTS (SELECT 1 FROM favorites f
               WHERE f.user_id = $1 AND f.entity_type = 'track'
                 AND f.entity_id = te.id) AS favorite
FROM playlist_tracks pt
JOIN tracks_effective te ON te.id = pt.track_id
WHERE pt.playlist_id = $2
ORDER BY pt.position, pt.id
`

type ListPlaylistTracksParams struct {
	UserID     uuid.UUID
	PlaylistID uuid.UUID
}

type ListPlaylistTracksRow struct {
	EntryID         uuid.UUID
	Position        int32
	AddedAt         time.Time
	ID              uuid.UUID
	RootID          uuid.UUID
	RelPath         string
	Size            int64
	Mtime           time.Time
	ContentHash     []byte
	DurationMs      *int32
	Bitrate         *int32
	SampleRate      *int32
	Channels        *int16
	Codec           *string
	Suffix          string
	AlbumID         pgtype.UUID
	ArtistID        pgtype.UUID
	AlbumArtistID   pgtype.UUID
	CoverArtID      pgtype.UUID
	MissingAt       pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Title           string
	TrackNo         *int32
	DiscNo          *int32
	Year            *int32
	ArtistName      string
	AlbumName       string
	AlbumArtistName string
	Unavailable     bool
	Genres          []string
	Favorite        bool
}

// ---- playlist contents ----------------------------------------------------------
// Missing tracks are kept in the listing rather than filtered out: a playlist
// entry pointing at an unmounted drive should show as unavailable, not silently
// vanish and leave the owner wondering what they deleted.
func (q *Queries) ListPlaylistTracks(ctx context.Context, arg ListPlaylistTracksParams) ([]ListPlaylistTracksRow, error) {
	rows, err := q.db.Query(ctx, listPlaylistTracks, arg.UserID, arg.PlaylistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaylistTracksRow{}
	for rows.Next() {
		var i ListPlaylistTracksRow
		if err := rows.Scan(
			&i.EntryID,
			&i.Position,
			&i.AddedAt,
			&i.ID,
			&i.RootID,
			&i.RelPath,
			&i.Size,
			&i.Mtime,
			&i.ContentHash,
			&i.DurationMs,
			&i.Bitrate,
			&i.SampleRate,
			&i.Channels,
			&i.Codec,
			&i.Suffix,
			&i.AlbumID,
			&i.ArtistID,
			&i.AlbumArtistID,
			&i.CoverArtID,
			&i.MissingAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.TrackNo,
			&i.DiscNo,
			&i.Year,
			&i.ArtistName,
			&i.AlbumName,
			&i.AlbumArtistName,
			&i.Unavailable,
			&i.Genres,
			&i.Favorite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylists = `-- name: ListPlaylists :many
SELECT p.id, p.user_id, p.name, p.description, p.public, p.created_at, p.updated_at,
       (p.user_id = $1) AS owned,
       u.display_name AS owner_name,
       count(pt.id)::bigint AS track_count,
       COALESCE(sum(t.duration_ms), 0)::bigint AS duration_ms
FROM playlists p
JOIN users u ON u.id = p.user_id
LEFT JOIN playlist_tracks pt ON pt.playlist_id = p.id
LEFT JOIN tracks t ON t.id = pt.track_id AND t.missing_at IS NULL
WHERE p.user_id = $1 OR p.public
GROUP BY p.id, u.display_name
ORDER BY lower(p.name), p.id
`

type ListPlaylistsRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description string
	Public      bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Owned       bool
	OwnerName   string
	TrackCount  int64
	DurationMs  int64
}

// Own playlists, plus anyone's public ones. Ownership is returned so the client
// can tell which are editable without a second lookup.
func (q *Queries) ListPlaylists(ctx context.Context, userID uuid.UUID) ([]ListPlaylistsRow, error) {
	rows, err := q.db.Query(ctx, listPlaylists, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaylistsRow{}
	for rows.Next() {
		var i ListPlaylistsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Public,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Owned,
			&i.OwnerName,
			&i.TrackCount,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const playlistContainsTrack = `-- name: PlaylistContainsTrack :one
SELECT EXISTS (
    SELECT 1 FROM playlist_tracks WHERE playlist_id = $1 AND track_id = $2
)
`

type PlaylistContainsTrackParams struct {
	PlaylistID uuid.UUID
	TrackID    uuid.UUID
}

// Adding a track that is already present is allowed, but only deliberately:
// the API refuses it unless the caller confirms, so a mis-click cannot quietly
// duplicate an entry.
func (q *Queries) PlaylistContainsTrack(ctx context.Context, arg PlaylistContainsTrackParams) (bool, error) {
	row := q.db.QueryRow(ctx, playlistContainsTrack, arg.PlaylistID, arg.TrackID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const playlistIsOwnedBy = `-- name: PlaylistIsOwnedBy :one
SELECT EXISTS (SELECT 1 FROM playlists WHERE id = $1 AND user_id = $2)
`

type PlaylistIsOwnedByParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) PlaylistIsOwnedBy(ctx context.Context, arg PlaylistIsOwnedByParams) (bool, error) {
	row := q.db.QueryRow(ctx, playlistIsOwnedBy, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const recordPlay = `-- name: RecordPlay :one

INSERT INTO plays (user_id, track_id, ms_played, source)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, track_id, played_at, ms_played, source
`

type RecordPlayParams struct {
	UserID   uuid.UUID
	TrackID  pgtype.UUID
	MsPlayed int32
	Source   string
}

// ---- plays ------------------------------------------------------------------------
func (q *Queries) RecordPlay(ctx context.Context, arg RecordPlayParams) (Play, error) {
	row := q.db.QueryRow(ctx, recordPlay,
		arg.UserID,
		arg.TrackID,
		arg.MsPlayed,
		arg.Source,
	)
	var i Play
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackID,
		&i.PlayedAt,
		&i.MsPlayed,
		&i.Source,
	)
	return i, err
}

const removeFavorite = `-- name: RemoveFavorite :execrows
DELETE FROM favorites WHERE user_id = $1 AND entity_type = $2 AND entity_id = $3
`

type RemoveFavoriteParams struct {
	UserID     uuid.UUID
	EntityType FavoriteEntity
	EntityID   uuid.UUID
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.EntityType, arg.EntityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removePlaylistTrack = `-- name: RemovePlaylistTrack :execrows
DELETE FROM playlist_tracks WHERE id = $1 AND playlist_id = $2
`

type RemovePlaylistTrackParams struct {
	ID         uuid.UUID
	PlaylistID uuid.UUID
}

func (q *Queries) RemovePlaylistTrack(ctx context.Context, arg RemovePlaylistTrackParams) (int64, error) {
	result, err := q.db.Exec(ctx, removePlaylistTrack, arg.ID, arg.PlaylistID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reorderPlaylist = `-- name: ReorderPlaylist :exec
UPDATE playlist_tracks pt
SET position = new_order.position
FROM (
    SELECT unnest($2::uuid[]) AS id,
           generate_subscripts($2::uuid[], 1) - 1 AS position
) AS new_order
WHERE pt.id = new_order.id AND pt.playlist_id = $1
`

type ReorderPlaylistParams struct {
	PlaylistID uuid.UUID
	EntryIds   []uuid.UUID
}

// Applies a whole new order in one statement. The unique constraint on
// (playlist_id, position) is deferrable precisely so this can pass through
// intermediate states where two rows briefly share a position.
func (q *Queries) ReorderPlaylist(ctx context.Context, arg ReorderPlaylistParams) error {
	_, err := q.db.Exec(ctx, reorderPlaylist, arg.PlaylistID, arg.EntryIds)
	return err
}

const topTracks = `-- name: TopTracks :many
SELECT te.id, te.root_id, te.rel_path, te.size, te.mtime, te.content_hash, te.duration_ms, te.bitrate, te.sample_rate, te.channels, te.codec, te.suffix, te.album_id, te.artist_id, te.album_artist_id, te.cover_art_id, te.missing_at, te.created_at, te.updated_at, te.title, te.track_no, te.disc_no, te.year, te.artist_name, te.album_name, te.album_artist_name,
       (SELECT COALESCE(array_agg(g.name ORDER BY g.name), '{}')
        FROM track_genres tg JOIN genres g ON g.id = tg.genre_id
        WHERE tg.track_id = te.id)::text[] AS genres,
       count(p.id)::bigint AS play_count
FROM plays p
JOIN tracks_effective te ON te.id = p.track_id
WHERE p.user_id = $1 AND te.missing_at IS NULL
GROUP BY te.id, te.root_id, te.rel_path, te.size, te.mtime, te.content_hash,
         te.duration_ms, te.bitrate, te.sample_rate, te.channels, te.codec,
         te.suffix, te.album_id, te.artist_id, te.album_artist_id,
         te.cover_art_id, te.missing_at, te.created_at, te.updated_at,
         te.title, te.track_no, te.disc_no, te.year, te.artist_name,
         te.album_name, te.album_artist_name
ORDER BY play_count DESC, lower(te.title)
LIMIT $2
`

type TopTracksParams struct {
	UserID uuid.UUID
	Limit  int32
}

type TopTracksRow struct {
	ID              uuid.UUID
	RootID          uuid.UUID
	RelPath         string
	Size            int64
	Mtime           time.Time
	ContentHash     []byte
	DurationMs      *int32
	Bitrate         *int32
	SampleRate      *int32
	Channels        *int16
	Codec           *string
	Suffix          string
	AlbumID         pgtype.UUID
	ArtistID        pgtype.UUID
	AlbumArtistID   pgtype.UUID
	CoverArtID      pgtype.UUID
	MissingAt       pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Title           string
	TrackNo         *int32
	DiscNo          *int32
	Year            *int32
	ArtistName      string
	AlbumName       string
	AlbumArtistName string
	Genres          []string
	PlayCount       int64
}

func (q *Queries) TopTracks(ctx context.Context, arg TopTracksParams) ([]TopTracksRow, error) {
	rows, err := q.db.Query(ctx, topTracks, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopTracksRow{}
	for rows.Next() {
		var i TopTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.RootID,
			&i.RelPath,
			&i.Size,
			&i.Mtime,
			&i.ContentHash,
			&i.DurationMs,
			&i.Bitrate,
			&i.SampleRate,
			&i.Channels,
			&i.Codec,
			&i.Suffix,
			&i.AlbumID,
			&i.ArtistID,
			&i.AlbumArtistID,
			&i.CoverArtID,
			&i.MissingAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.TrackNo,
			&i.DiscNo,
			&i.Year,
			&i.ArtistName,
			&i.AlbumName,
			&i.AlbumArtistName,
			&i.Genres,
			&i.PlayCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackPlayStats = `-- name: TrackPlayStats :one
SELECT count(*)::bigint AS play_count, max(played_at) AS last_played_at
FROM plays WHERE user_id = $1 AND track_id = $2
`

type TrackPlayStatsParams struct {
	UserID  uuid.UUID
	TrackID pgtype.UUID
}

type TrackPlayStatsRow struct {
	PlayCount    int64
	LastPlayedAt interface{}
}

func (q *Queries) TrackPlayStats(ctx context.Context, arg TrackPlayStatsParams) (TrackPlayStatsRow, error) {
	row := q.db.QueryRow(ctx, trackPlayStats, arg.UserID, arg.TrackID)
	var i TrackPlayStatsRow
	err := row.Scan(&i.PlayCount, &i.LastPlayedAt)
	return i, err
}

const updatePlaylist = `-- name: UpdatePlaylist :one
UPDATE playlists
SET name        = COALESCE($1::text, name),
    description = COALESCE($2::text, description),
    public      = COALESCE($3::bool, public),
    updated_at  = now()
WHERE id = $4 AND user_id = $5
RETURNING id, user_id, name, description, public, created_at, updated_at
`

type UpdatePlaylistParams struct {
	Name        *string
	Description *string
	Public      *bool
	ID          uuid.UUID
	UserID      uuid.UUID
}

// Scoped by user_id so a non-owner's update silently matches nothing rather
// than needing a separate ownership check that a caller could forget.
func (q *Queries) UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (Playlist, error) {
	row := q.db.QueryRow(ctx, updatePlaylist,
		arg.Name,
		arg.Description,
		arg.Public,
		arg.ID,
		arg.UserID,
	)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
