// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ---- favorites ------------------------------------------------------------------
	AddFavorite(ctx context.Context, arg AddFavoriteParams) error
	// Appends at the end. The position is computed in the same statement so two
	// concurrent adds cannot both read the same max and collide.
	AppendPlaylistTrack(ctx context.Context, arg AppendPlaylistTrackParams) (PlaylistTrack, error)
	// The canonical multi-worker claim. SKIP LOCKED lets every worker drain the
	// queue concurrently without contending on the same row or double-claiming.
	ClaimJob(ctx context.Context) (Job, error)
	ClearTrackOverride(ctx context.Context, trackID uuid.UUID) error
	// Renumbers from zero after a removal, so positions stay dense and the next
	// append lands where it should.
	CompactPlaylistPositions(ctx context.Context, playlistID uuid.UUID) error
	// Clearing dedupe_key on completion lets the same logical work be enqueued
	// again later; leaving it would make the unique index reject every future
	// enqueue for that key.
	CompleteJob(ctx context.Context, id uuid.UUID) error
	// Guards the last-admin check. Counts only admins who can still sign in.
	CountActiveAdmins(ctx context.Context) (int64, error)
	CountJobsByState(ctx context.Context) ([]CountJobsByStateRow, error)
	CountPlaylistTracks(ctx context.Context, playlistID uuid.UUID) (int64, error)
	// ---- counts -----------------------------------------------------------------
	CountTracks(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// ---- playlists ----------------------------------------------------------------
	CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteFinishedJobsBefore(ctx context.Context, olderThan pgtype.Interval) (int64, error)
	// Cutoff computed server-side, for the same reason run_after is: the database
	// clock is the only one that matters here.
	DeleteMissingTracksOlderThan(ctx context.Context, olderThan pgtype.Interval) (int64, error)
	// Albums and artists are swept in two statements, deliberately. A single
	// statement with a CTE cannot work: every part of it sees the same snapshot, so
	// the artist check would still see the albums the CTE is deleting and spare
	// every artist whose only album just went away.
	DeleteOrphanedAlbums(ctx context.Context) (int64, error)
	DeleteOrphanedArtists(ctx context.Context) (int64, error)
	// Rows that no track references any more. Cover art is content-addressed and
	// shared, so it can only be removed once nothing points at it.
	DeleteOrphanedCoverArt(ctx context.Context) ([]string, error)
	DeletePlaylist(ctx context.Context, arg DeletePlaylistParams) (int64, error)
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteSessionsForUser(ctx context.Context, userID uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	// Enqueue is idempotent on dedupe_key: a watcher firing several events for one
	// file write produces one job. Touching run_after on conflict lets a repeated
	// event push the work later, which is what debouncing an active writer wants.
	// run_after is computed by the database, never by the caller. A client-supplied
	// timestamp makes scheduling depend on the app and database clocks agreeing: a
	// host a few milliseconds ahead produces jobs that are not yet claimable when
	// the NOTIFY arrives, so every one of them waits for the next poll instead.
	EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error)
	// ---- eviction ------------------------------------------------------------------
	// Promoted items are excluded everywhere in this section: their bytes live
	// under a library root now, not in the disposable cache.
	ExpiredYTItems(ctx context.Context) ([]YtItem, error)
	// Move detection: a file whose content hash matches a row that is now missing,
	// or whose recorded path no longer exists, is the same track relocated.
	FindTrackByHash(ctx context.Context, arg FindTrackByHashParams) (Track, error)
	GetAlbum(ctx context.Context, id uuid.UUID) (GetAlbumRow, error)
	// Album art is requested by album far more often than by its own id, so this
	// saves the client a lookup it would otherwise always have to make first.
	GetAlbumCoverArt(ctx context.Context, id uuid.UUID) (GetAlbumCoverArtRow, error)
	GetArtist(ctx context.Context, id uuid.UUID) (GetArtistRow, error)
	GetCoverArt(ctx context.Context, id uuid.UUID) (GetCoverArtRow, error)
	GetJob(ctx context.Context, id uuid.UUID) (Job, error)
	GetLibraryRoot(ctx context.Context, id uuid.UUID) (LibraryRoot, error)
	GetPlaylist(ctx context.Context, arg GetPlaylistParams) (GetPlaylistRow, error)
	// Resolves a bearer token to its session and owner in one round trip, and
	// filters out expired sessions and disabled accounts so callers cannot forget
	// to. Returning no row is the only "not authenticated" signal handlers need.
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error)
	GetTrack(ctx context.Context, arg GetTrackParams) (GetTrackRow, error)
	GetTrackByPath(ctx context.Context, arg GetTrackByPathParams) (Track, error)
	// Duration is needed server-side to decide whether a reported play qualifies;
	// trusting the client's number would let anyone inflate their own counts.
	GetTrackDuration(ctx context.Context, id uuid.UUID) (*int32, error)
	// Everything needed to serve one track's bytes, in a single round trip: the
	// root path and relative path that locate the file, plus the metadata the
	// response headers need.
	GetTrackForStream(ctx context.Context, id uuid.UUID) (GetTrackForStreamRow, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Subject lookups come first in the sign-in path: an IdP subject is stable
	// even when the user changes their email address at the provider.
	GetUserByGoogleSub(ctx context.Context, googleSub *string) (User, error)
	GetUserByOIDCSub(ctx context.Context, oidcSub *string) (User, error)
	GetYTItem(ctx context.Context, videoID string) (YtItem, error)
	IsFavorite(ctx context.Context, arg IsFavoriteParams) (bool, error)
	LibraryStats(ctx context.Context) (LibraryStatsRow, error)
	// Attaches a provider subject to an account found by email, so that signing in
	// with Google and then with a self-hosted IdP lands on one account rather than
	// creating a second. Only fills an empty column: a subject already recorded is
	// left alone so a different provider account cannot claim an existing user.
	LinkGoogleSub(ctx context.Context, arg LinkGoogleSubParams) (User, error)
	LinkOIDCSub(ctx context.Context, arg LinkOIDCSubParams) (User, error)
	// Disc then track number, which is the only order an album makes sense in.
	ListAlbumTracks(ctx context.Context, arg ListAlbumTracksParams) ([]ListAlbumTracksRow, error)
	// ---- albums -------------------------------------------------------------------
	ListAlbums(ctx context.Context, arg ListAlbumsParams) ([]ListAlbumsRow, error)
	// ---- artists ------------------------------------------------------------------
	// Only artists with at least one live track: reconciliation can leave rows
	// behind, and a browse list full of entries that match nothing is noise.
	ListArtists(ctx context.Context, arg ListArtistsParams) ([]ListArtistsRow, error)
	ListFavoriteTracks(ctx context.Context, arg ListFavoriteTracksParams) ([]ListFavoriteTracksRow, error)
	// ---- genres -------------------------------------------------------------------
	ListGenres(ctx context.Context) ([]ListGenresRow, error)
	ListHistory(ctx context.Context, arg ListHistoryParams) ([]ListHistoryRow, error)
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error)
	ListLibraryRoots(ctx context.Context) ([]LibraryRoot, error)
	// ---- playlist contents ----------------------------------------------------------
	// Missing tracks are kept in the listing rather than filtered out: a playlist
	// entry pointing at an unmounted drive should show as unavailable, not silently
	// vanish and leave the owner wondering what they deleted.
	ListPlaylistTracks(ctx context.Context, arg ListPlaylistTracksParams) ([]ListPlaylistTracksRow, error)
	// Own playlists, plus anyone's public ones. Ownership is returned so the client
	// can tell which are editable without a second lookup.
	ListPlaylists(ctx context.Context, userID uuid.UUID) ([]ListPlaylistsRow, error)
	// ---- tracks -----------------------------------------------------------------
	// Returns just enough to decide whether a file changed, without loading whole
	// rows for a library that is mostly unchanged.
	ListTrackStatsForRoot(ctx context.Context, rootID uuid.UUID) ([]ListTrackStatsForRootRow, error)
	// Read paths for browsing and searching the library.
	//
	// Every listing is keyset-paginated on (sort key, id). Offset pagination
	// degrades badly past a few thousand rows and double-serves items when the
	// library changes mid-scroll, which it does constantly while a scan runs.
	// ---- tracks -------------------------------------------------------------------
	// The one query behind GET /tracks. Each filter is inert when its parameter is
	// NULL, so one statement serves every combination the API allows rather than a
	// combinatorial set of near-identical queries.
	//
	// The cursor predicate is a row comparison rather than OR-ed inequalities:
	// (sort_key, id) > (last_sort_key, last_id) uses the composite index directly,
	// where the expanded form usually will not.
	ListTracks(ctx context.Context, arg ListTracksParams) ([]ListTracksRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListYTItems(ctx context.Context, limit int32) ([]ListYTItemsRow, error)
	MarkScanFinished(ctx context.Context, arg MarkScanFinishedParams) error
	MarkScanStarted(ctx context.Context, id uuid.UUID) error
	MarkTracksMissing(ctx context.Context, ids []uuid.UUID) (int64, error)
	MarkYTDownloading(ctx context.Context, videoID string) error
	MarkYTEvicted(ctx context.Context, videoID string) error
	MarkYTFailed(ctx context.Context, arg MarkYTFailedParams) error
	// ---- promotion -----------------------------------------------------------------
	MarkYTPromoted(ctx context.Context, arg MarkYTPromotedParams) error
	// Both timestamps are computed server-side, for the same reason job scheduling
	// is: the database clock is the only one that matters.
	MarkYTReady(ctx context.Context, arg MarkYTReadyParams) (YtItem, error)
	// Relocating a track keeps its id, and therefore its playlist entries and play
	// history, across a library reorganisation.
	MoveTrack(ctx context.Context, arg MoveTrackParams) (Track, error)
	// Adding a track that is already present is allowed, but only deliberately:
	// the API refuses it unless the caller confirms, so a mis-click cannot quietly
	// duplicate an entry.
	PlaylistContainsTrack(ctx context.Context, arg PlaylistContainsTrackParams) (bool, error)
	PlaylistIsOwnedBy(ctx context.Context, arg PlaylistIsOwnedByParams) (bool, error)
	// Rebuilds a track's search text from its effective values.
	//
	// This is the single definition of the haystack, used by both the scanner and
	// the override editor. Assembling it in Go as well would let the two drift, and
	// the symptom would be a track that is unfindable by the name shown for it.
	RebuildTrackSearch(ctx context.Context, id uuid.UUID) error
	// ---- plays ------------------------------------------------------------------------
	RecordPlay(ctx context.Context, arg RecordPlayParams) (Play, error)
	RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) (int64, error)
	RemovePlaylistTrack(ctx context.Context, arg RemovePlaylistTrackParams) (int64, error)
	// Applies a whole new order in one statement. The unique constraint on
	// (playlist_id, position) is deferrable precisely so this can pass through
	// intermediate states where two rows briefly share a position.
	ReorderPlaylist(ctx context.Context, arg ReorderPlaylistParams) error
	ReplaceTrackGenres(ctx context.Context, arg ReplaceTrackGenresParams) error
	// Requeues jobs left 'running' by a process that died. Without this a crash
	// during a scan strands the work forever, since nothing else revisits a row
	// that was already claimed.
	RequeueStaleJobs(ctx context.Context, staleAfter pgtype.Interval) (int64, error)
	// A job below its attempt ceiling goes back to 'queued' with a backoff;
	// otherwise it is terminal.
	RetryOrFailJob(ctx context.Context, arg RetryOrFailJobParams) (Job, error)
	SearchAlbums(ctx context.Context, arg SearchAlbumsParams) ([]SearchAlbumsRow, error)
	SearchArtists(ctx context.Context, arg SearchArtistsParams) ([]SearchArtistsRow, error)
	// ---- search -------------------------------------------------------------------
	// Ranked full-text search. websearch_to_tsquery accepts what a person actually
	// types — bare words, quoted phrases, "or" — without erroring on punctuation
	// the way to_tsquery does.
	SearchTracksExact(ctx context.Context, arg SearchTracksExactParams) ([]SearchTracksExactRow, error)
	// Trigram fallback, for when exact matching finds too little: typos
	// ("radiohed"), partial words, and missing diacritics. Deliberately a separate
	// query rather than an OR — combining them would stop Postgres using either
	// index and turn every search into a sequential scan.
	//
	// word_similarity, not similarity: the latter compares whole strings, so a
	// short query against a long haystack ("Airbag Radiohead OK Computer
	// Alternative Rock") scores far below any usable threshold and matches
	// nothing. The <% operator asks instead whether the query closely matches some
	// run of words *inside* the haystack, which is what a search box means.
	SearchTracksFuzzy(ctx context.Context, arg SearchTracksFuzzyParams) ([]SearchTracksFuzzyRow, error)
	// Queries with no table dependencies. Their real job in M0 is to keep the
	// sqlc pipeline exercised before the schema exists; ServerTime is also a
	// genuine readiness probe, since it proves a round trip rather than just a
	// reachable socket the way Ping does.
	ServerTime(ctx context.Context) (time.Time, error)
	TopTracks(ctx context.Context, arg TopTracksParams) ([]TopTracksRow, error)
	// Throttled by the caller to avoid a write on every request.
	TouchSession(ctx context.Context, id uuid.UUID) error
	// Sliding window: every play pushes the expiry out, capped so a single
	// much-played item cannot hold cache space forever.
	TouchYTItem(ctx context.Context, arg TouchYTItemParams) error
	TrackPlayStats(ctx context.Context, arg TrackPlayStatsParams) (TrackPlayStatsRow, error)
	// Scoped by user_id so a non-owner's update silently matches nothing rather
	// than needing a separate ownership check that a caller could forget.
	UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (Playlist, error)
	// Refreshes the profile fields an IdP owns on every sign-in, so a renamed or
	// re-avatared account stays current without a separate sync.
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (User, error)
	// Partial update for the admin API.
	//
	// password_hash and role use COALESCE with a nullable parameter, so NULL means
	// "leave unchanged". A boolean flag with a non-nullable parameter cannot work
	// for role: Postgres coerces the bound value to user_role while planning, so
	// an unused ''::user_role fails even inside a CASE branch that is never taken.
	//
	// disabled_at genuinely needs a flag, because NULL is a meaningful target
	// value there — it is how an account gets re-enabled.
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertAlbum(ctx context.Context, arg UpsertAlbumParams) (Album, error)
	// ---- reconciliation ---------------------------------------------------------
	// Reconciliation is by normalised name, so "The Beatles" and "Beatles" collapse
	// to one artist. ON CONFLICT DO UPDATE rather than DO NOTHING because a bare
	// DO NOTHING returns no row on conflict, which would cost a second round trip
	// on the overwhelmingly common already-exists path.
	// Variants that normalise together share a row, so one of them has to supply
	// the display name. Keeping whichever inserted first makes that a race between
	// scanner workers — the same library could show "The Beatles" or "Beatles"
	// depending on file order. Preferring the longer form is both deterministic and
	// usually the more complete name.
	UpsertArtist(ctx context.Context, arg UpsertArtistParams) (Artist, error)
	UpsertCoverArt(ctx context.Context, arg UpsertCoverArtParams) (CoverArt, error)
	UpsertGenre(ctx context.Context, name string) (Genre, error)
	// ---- roots -----------------------------------------------------------------
	UpsertLibraryRoot(ctx context.Context, arg UpsertLibraryRootParams) (LibraryRoot, error)
	UpsertTrack(ctx context.Context, arg UpsertTrackParams) (Track, error)
	// ---- overrides ----------------------------------------------------------------
	UpsertTrackOverride(ctx context.Context, arg UpsertTrackOverrideParams) (TrackOverride, error)
	// Written in the same transaction as the track, from the effective values.
	UpsertTrackSearch(ctx context.Context, arg UpsertTrackSearchParams) error
	UpsertYTItem(ctx context.Context, arg UpsertYTItemParams) (YtItem, error)
	YTCacheBytes(ctx context.Context) (int64, error)
	// Least recently used first, which is the order to reclaim space in.
	YTItemsByLRU(ctx context.Context, limit int32) ([]YtItem, error)
}

var _ Querier = (*Queries)(nil)
