// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// The canonical multi-worker claim. SKIP LOCKED lets every worker drain the
	// queue concurrently without contending on the same row or double-claiming.
	ClaimJob(ctx context.Context) (Job, error)
	// Clearing dedupe_key on completion lets the same logical work be enqueued
	// again later; leaving it would make the unique index reject every future
	// enqueue for that key.
	CompleteJob(ctx context.Context, id uuid.UUID) error
	// Guards the last-admin check. Counts only admins who can still sign in.
	CountActiveAdmins(ctx context.Context) (int64, error)
	CountJobsByState(ctx context.Context) ([]CountJobsByStateRow, error)
	// ---- counts -----------------------------------------------------------------
	CountTracks(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteFinishedJobsBefore(ctx context.Context, olderThan pgtype.Interval) (int64, error)
	// Cutoff computed server-side, for the same reason run_after is: the database
	// clock is the only one that matters here.
	DeleteMissingTracksOlderThan(ctx context.Context, olderThan pgtype.Interval) (int64, error)
	// Albums and artists are swept in two statements, deliberately. A single
	// statement with a CTE cannot work: every part of it sees the same snapshot, so
	// the artist check would still see the albums the CTE is deleting and spare
	// every artist whose only album just went away.
	DeleteOrphanedAlbums(ctx context.Context) (int64, error)
	DeleteOrphanedArtists(ctx context.Context) (int64, error)
	// Rows that no track references any more. Cover art is content-addressed and
	// shared, so it can only be removed once nothing points at it.
	DeleteOrphanedCoverArt(ctx context.Context) ([]string, error)
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteSessionsForUser(ctx context.Context, userID uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	// Enqueue is idempotent on dedupe_key: a watcher firing several events for one
	// file write produces one job. Touching run_after on conflict lets a repeated
	// event push the work later, which is what debouncing an active writer wants.
	// run_after is computed by the database, never by the caller. A client-supplied
	// timestamp makes scheduling depend on the app and database clocks agreeing: a
	// host a few milliseconds ahead produces jobs that are not yet claimable when
	// the NOTIFY arrives, so every one of them waits for the next poll instead.
	EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error)
	// Move detection: a file whose content hash matches a row that is now missing,
	// or whose recorded path no longer exists, is the same track relocated.
	FindTrackByHash(ctx context.Context, arg FindTrackByHashParams) (Track, error)
	GetJob(ctx context.Context, id uuid.UUID) (Job, error)
	GetLibraryRoot(ctx context.Context, id uuid.UUID) (LibraryRoot, error)
	// Resolves a bearer token to its session and owner in one round trip, and
	// filters out expired sessions and disabled accounts so callers cannot forget
	// to. Returning no row is the only "not authenticated" signal handlers need.
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error)
	GetTrackByPath(ctx context.Context, arg GetTrackByPathParams) (Track, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Subject lookups come first in the sign-in path: an IdP subject is stable
	// even when the user changes their email address at the provider.
	GetUserByGoogleSub(ctx context.Context, googleSub *string) (User, error)
	GetUserByOIDCSub(ctx context.Context, oidcSub *string) (User, error)
	LibraryStats(ctx context.Context) (LibraryStatsRow, error)
	// Attaches a provider subject to an account found by email, so that signing in
	// with Google and then with a self-hosted IdP lands on one account rather than
	// creating a second. Only fills an empty column: a subject already recorded is
	// left alone so a different provider account cannot claim an existing user.
	LinkGoogleSub(ctx context.Context, arg LinkGoogleSubParams) (User, error)
	LinkOIDCSub(ctx context.Context, arg LinkOIDCSubParams) (User, error)
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error)
	ListLibraryRoots(ctx context.Context) ([]LibraryRoot, error)
	// ---- tracks -----------------------------------------------------------------
	// Returns just enough to decide whether a file changed, without loading whole
	// rows for a library that is mostly unchanged.
	ListTrackStatsForRoot(ctx context.Context, rootID uuid.UUID) ([]ListTrackStatsForRootRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkScanFinished(ctx context.Context, arg MarkScanFinishedParams) error
	MarkScanStarted(ctx context.Context, id uuid.UUID) error
	MarkTracksMissing(ctx context.Context, ids []uuid.UUID) (int64, error)
	// Relocating a track keeps its id, and therefore its playlist entries and play
	// history, across a library reorganisation.
	MoveTrack(ctx context.Context, arg MoveTrackParams) (Track, error)
	ReplaceTrackGenres(ctx context.Context, arg ReplaceTrackGenresParams) error
	// Requeues jobs left 'running' by a process that died. Without this a crash
	// during a scan strands the work forever, since nothing else revisits a row
	// that was already claimed.
	RequeueStaleJobs(ctx context.Context, staleAfter pgtype.Interval) (int64, error)
	// A job below its attempt ceiling goes back to 'queued' with a backoff;
	// otherwise it is terminal.
	RetryOrFailJob(ctx context.Context, arg RetryOrFailJobParams) (Job, error)
	// Queries with no table dependencies. Their real job in M0 is to keep the
	// sqlc pipeline exercised before the schema exists; ServerTime is also a
	// genuine readiness probe, since it proves a round trip rather than just a
	// reachable socket the way Ping does.
	ServerTime(ctx context.Context) (time.Time, error)
	// Throttled by the caller to avoid a write on every request.
	TouchSession(ctx context.Context, id uuid.UUID) error
	// Refreshes the profile fields an IdP owns on every sign-in, so a renamed or
	// re-avatared account stays current without a separate sync.
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (User, error)
	// Partial update for the admin API.
	//
	// password_hash and role use COALESCE with a nullable parameter, so NULL means
	// "leave unchanged". A boolean flag with a non-nullable parameter cannot work
	// for role: Postgres coerces the bound value to user_role while planning, so
	// an unused ''::user_role fails even inside a CASE branch that is never taken.
	//
	// disabled_at genuinely needs a flag, because NULL is a meaningful target
	// value there — it is how an account gets re-enabled.
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertAlbum(ctx context.Context, arg UpsertAlbumParams) (Album, error)
	// ---- reconciliation ---------------------------------------------------------
	// Reconciliation is by normalised name, so "The Beatles" and "Beatles" collapse
	// to one artist. ON CONFLICT DO UPDATE rather than DO NOTHING because a bare
	// DO NOTHING returns no row on conflict, which would cost a second round trip
	// on the overwhelmingly common already-exists path.
	UpsertArtist(ctx context.Context, arg UpsertArtistParams) (Artist, error)
	UpsertCoverArt(ctx context.Context, arg UpsertCoverArtParams) (CoverArt, error)
	UpsertGenre(ctx context.Context, name string) (Genre, error)
	// ---- roots -----------------------------------------------------------------
	UpsertLibraryRoot(ctx context.Context, arg UpsertLibraryRootParams) (LibraryRoot, error)
	UpsertTrack(ctx context.Context, arg UpsertTrackParams) (Track, error)
	// Written in the same transaction as the track, from the effective values.
	UpsertTrackSearch(ctx context.Context, arg UpsertTrackSearchParams) error
}

var _ Querier = (*Queries)(nil)
