// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, csrf_token, user_agent, ip, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, token_hash, csrf_token, user_agent, ip, created_at, last_seen_at, expires_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID
	TokenHash []byte
	CsrfToken string
	UserAgent *string
	Ip        *netip.Addr
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.CsrfToken,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfToken,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsForUser, userID)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT sessions.id, sessions.user_id, sessions.token_hash, sessions.csrf_token, sessions.user_agent, sessions.ip, sessions.created_at, sessions.last_seen_at, sessions.expires_at, users.id, users.email, users.display_name, users.avatar_url, users.google_sub, users.oidc_sub, users.password_hash, users.role, users.created_at, users.updated_at, users.disabled_at
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1
  AND sessions.expires_at > now()
  AND users.disabled_at IS NULL
`

type GetSessionByTokenHashRow struct {
	Session Session
	User    User
}

// Resolves a bearer token to its session and owner in one round trip, and
// filters out expired sessions and disabled accounts so callers cannot forget
// to. Returning no row is the only "not authenticated" signal handlers need.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.TokenHash,
		&i.Session.CsrfToken,
		&i.Session.UserAgent,
		&i.Session.Ip,
		&i.Session.CreatedAt,
		&i.Session.LastSeenAt,
		&i.Session.ExpiresAt,
		&i.User.ID,
		&i.User.Email,
		&i.User.DisplayName,
		&i.User.AvatarUrl,
		&i.User.GoogleSub,
		&i.User.OidcSub,
		&i.User.PasswordHash,
		&i.User.Role,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.DisabledAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now() WHERE id = $1
`

// Throttled by the caller to avoid a write on every request.
func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}
