// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package dbgen

import (
	"context"
	"time"
)

const serverTime = `-- name: ServerTime :one

SELECT now()::timestamptz AS server_time
`

// Queries with no table dependencies. Their real job in M0 is to keep the
// sqlc pipeline exercised before the schema exists; ServerTime is also a
// genuine readiness probe, since it proves a round trip rather than just a
// reachable socket the way Ping does.
func (q *Queries) ServerTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, serverTime)
	var server_time time.Time
	err := row.Scan(&server_time)
	return server_time, err
}
