// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(*) FROM users
WHERE role = 'admin' AND disabled_at IS NULL
`

// Guards the last-admin check. Counts only admins who can still sign in.
func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, avatar_url, google_sub, oidc_sub, password_hash, role)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, display_name, avatar_url, google_sub, oidc_sub, password_hash, role, created_at, updated_at, disabled_at
`

type CreateUserParams struct {
	Email        string
	DisplayName  string
	AvatarUrl    *string
	GoogleSub    *string
	OidcSub      *string
	PasswordHash *string
	Role         UserRole
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.GoogleSub,
		arg.OidcSub,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleSub,
		&i.OidcSub,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUser = `-- name: GetUser :one
SELECT id, email, display_name, avatar_url, google_sub, oidc_sub, password_hash, role, created_at, updated_at, disabled_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleSub,
		&i.OidcSub,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, avatar_url, google_sub, oidc_sub, password_hash, role, created_at, updated_at, disabled_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleSub,
		&i.OidcSub,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getUserByGoogleSub = `-- name: GetUserByGoogleSub :one
SELECT id, email, display_name, avatar_url, google_sub, oidc_sub, password_hash, role, created_at, updated_at, disabled_at FROM users WHERE google_sub = $1
`

// Subject lookups come first in the sign-in path: an IdP subject is stable
// even when the user changes their email address at the provider.
func (q *Queries) GetUserByGoogleSub(ctx context.Context, googleSub *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSub, googleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleSub,
		&i.OidcSub,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getUserByOIDCSub = `-- name: GetUserByOIDCSub :one
SELECT id, email, display_name, avatar_url, google_sub, oidc_sub, password_hash, role, created_at, updated_at, disabled_at FROM users WHERE oidc_sub = $1
`

func (q *Queries) GetUserByOIDCSub(ctx context.Context, oidcSub *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOIDCSub, oidcSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleSub,
		&i.OidcSub,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const linkGoogleSub = `-- name: LinkGoogleSub :one
UPDATE users
SET google_sub   = COALESCE(google_sub, $1::text),
    display_name = CASE WHEN display_name = '' THEN $2::text
                        ELSE display_name END,
    avatar_url   = COALESCE($3::text, avatar_url),
    updated_at   = now()
WHERE id = $4
RETURNING id, email, display_name, avatar_url, google_sub, oidc_sub, password_hash, role, created_at, updated_at, disabled_at
`

type LinkGoogleSubParams struct {
	GoogleSub   string
	DisplayName string
	AvatarUrl   *string
	ID          uuid.UUID
}

// Attaches a provider subject to an account found by email, so that signing in
// with Google and then with a self-hosted IdP lands on one account rather than
// creating a second. Only fills an empty column: a subject already recorded is
// left alone so a different provider account cannot claim an existing user.
func (q *Queries) LinkGoogleSub(ctx context.Context, arg LinkGoogleSubParams) (User, error) {
	row := q.db.QueryRow(ctx, linkGoogleSub,
		arg.GoogleSub,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleSub,
		&i.OidcSub,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const linkOIDCSub = `-- name: LinkOIDCSub :one
UPDATE users
SET oidc_sub     = COALESCE(oidc_sub, $1::text),
    display_name = CASE WHEN display_name = '' THEN $2::text
                        ELSE display_name END,
    avatar_url   = COALESCE($3::text, avatar_url),
    updated_at   = now()
WHERE id = $4
RETURNING id, email, display_name, avatar_url, google_sub, oidc_sub, password_hash, role, created_at, updated_at, disabled_at
`

type LinkOIDCSubParams struct {
	OidcSub     string
	DisplayName string
	AvatarUrl   *string
	ID          uuid.UUID
}

func (q *Queries) LinkOIDCSub(ctx context.Context, arg LinkOIDCSubParams) (User, error) {
	row := q.db.QueryRow(ctx, linkOIDCSub,
		arg.OidcSub,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleSub,
		&i.OidcSub,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, display_name, avatar_url, google_sub, oidc_sub, password_hash, role, created_at, updated_at, disabled_at FROM users ORDER BY email
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.GoogleSub,
			&i.OidcSub,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE users
SET display_name = CASE WHEN $1::text <> '' THEN $1::text
                        ELSE display_name END,
    avatar_url   = COALESCE($2::text, avatar_url),
    updated_at   = now()
WHERE id = $3
RETURNING id, email, display_name, avatar_url, google_sub, oidc_sub, password_hash, role, created_at, updated_at, disabled_at
`

type UpdateProfileParams struct {
	DisplayName string
	AvatarUrl   *string
	ID          uuid.UUID
}

// Refreshes the profile fields an IdP owns on every sign-in, so a renamed or
// re-avatared account stays current without a separate sync.
func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateProfile, arg.DisplayName, arg.AvatarUrl, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleSub,
		&i.OidcSub,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET password_hash = COALESCE($1::text, password_hash),
    role          = COALESCE($2::user_role, role),
    disabled_at   = CASE WHEN $3::bool
                         THEN $4::timestamptz ELSE disabled_at END,
    updated_at    = now()
WHERE id = $5
RETURNING id, email, display_name, avatar_url, google_sub, oidc_sub, password_hash, role, created_at, updated_at, disabled_at
`

type UpdateUserParams struct {
	PasswordHash *string
	Role         *UserRole
	SetDisabled  bool
	DisabledAt   pgtype.Timestamptz
	ID           uuid.UUID
}

// Partial update for the admin API.
//
// password_hash and role use COALESCE with a nullable parameter, so NULL means
// "leave unchanged". A boolean flag with a non-nullable parameter cannot work
// for role: Postgres coerces the bound value to user_role while planning, so
// an unused ”::user_role fails even inside a CASE branch that is never taken.
//
// disabled_at genuinely needs a flag, because NULL is a meaningful target
// value there — it is how an account gets re-enabled.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.PasswordHash,
		arg.Role,
		arg.SetDisabled,
		arg.DisabledAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleSub,
		&i.OidcSub,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}
