// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: youtube.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const expiredYTItems = `-- name: ExpiredYTItems :many


SELECT id, video_id, title, uploader, duration_ms, thumbnail_url, state, error, blob_key, bytes, cached_at, last_accessed_at, expires_at, promoted_track_id, created_at, updated_at FROM yt_items
WHERE state = 'ready' AND promoted_track_id IS NULL AND expires_at <= now()
`

// ---- eviction ------------------------------------------------------------------
// Promoted items are excluded everywhere in this section: their bytes live
// under a library root now, not in the disposable cache.
func (q *Queries) ExpiredYTItems(ctx context.Context) ([]YtItem, error) {
	rows, err := q.db.Query(ctx, expiredYTItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []YtItem{}
	for rows.Next() {
		var i YtItem
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Title,
			&i.Uploader,
			&i.DurationMs,
			&i.ThumbnailUrl,
			&i.State,
			&i.Error,
			&i.BlobKey,
			&i.Bytes,
			&i.CachedAt,
			&i.LastAccessedAt,
			&i.ExpiresAt,
			&i.PromotedTrackID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYTItem = `-- name: GetYTItem :one
SELECT id, video_id, title, uploader, duration_ms, thumbnail_url, state, error, blob_key, bytes, cached_at, last_accessed_at, expires_at, promoted_track_id, created_at, updated_at FROM yt_items WHERE video_id = $1
`

func (q *Queries) GetYTItem(ctx context.Context, videoID string) (YtItem, error) {
	row := q.db.QueryRow(ctx, getYTItem, videoID)
	var i YtItem
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Title,
		&i.Uploader,
		&i.DurationMs,
		&i.ThumbnailUrl,
		&i.State,
		&i.Error,
		&i.BlobKey,
		&i.Bytes,
		&i.CachedAt,
		&i.LastAccessedAt,
		&i.ExpiresAt,
		&i.PromotedTrackID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listYTItems = `-- name: ListYTItems :many
SELECT y.id, y.video_id, y.title, y.uploader, y.duration_ms, y.thumbnail_url, y.state, y.error, y.blob_key, y.bytes, y.cached_at, y.last_accessed_at, y.expires_at, y.promoted_track_id, y.created_at, y.updated_at, t.id AS track_id
FROM yt_items y
LEFT JOIN tracks t ON t.id = y.promoted_track_id
WHERE y.state <> 'evicted'
ORDER BY y.updated_at DESC
LIMIT $1
`

type ListYTItemsRow struct {
	ID              uuid.UUID
	VideoID         string
	Title           string
	Uploader        string
	DurationMs      *int32
	ThumbnailUrl    *string
	State           YtState
	Error           *string
	BlobKey         *string
	Bytes           *int64
	CachedAt        pgtype.Timestamptz
	LastAccessedAt  pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	PromotedTrackID pgtype.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	TrackID         pgtype.UUID
}

func (q *Queries) ListYTItems(ctx context.Context, limit int32) ([]ListYTItemsRow, error) {
	rows, err := q.db.Query(ctx, listYTItems, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListYTItemsRow{}
	for rows.Next() {
		var i ListYTItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Title,
			&i.Uploader,
			&i.DurationMs,
			&i.ThumbnailUrl,
			&i.State,
			&i.Error,
			&i.BlobKey,
			&i.Bytes,
			&i.CachedAt,
			&i.LastAccessedAt,
			&i.ExpiresAt,
			&i.PromotedTrackID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrackID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markYTDownloading = `-- name: MarkYTDownloading :exec
UPDATE yt_items
SET state = 'downloading', error = NULL, updated_at = now()
WHERE video_id = $1
`

func (q *Queries) MarkYTDownloading(ctx context.Context, videoID string) error {
	_, err := q.db.Exec(ctx, markYTDownloading, videoID)
	return err
}

const markYTEvicted = `-- name: MarkYTEvicted :exec
UPDATE yt_items
SET state = 'evicted', blob_key = NULL, bytes = NULL,
    cached_at = NULL, expires_at = NULL, updated_at = now()
WHERE video_id = $1
`

func (q *Queries) MarkYTEvicted(ctx context.Context, videoID string) error {
	_, err := q.db.Exec(ctx, markYTEvicted, videoID)
	return err
}

const markYTFailed = `-- name: MarkYTFailed :exec
UPDATE yt_items
SET state = 'failed', error = $1::text, updated_at = now()
WHERE video_id = $2
`

type MarkYTFailedParams struct {
	Error   string
	VideoID string
}

func (q *Queries) MarkYTFailed(ctx context.Context, arg MarkYTFailedParams) error {
	_, err := q.db.Exec(ctx, markYTFailed, arg.Error, arg.VideoID)
	return err
}

const markYTPromoted = `-- name: MarkYTPromoted :exec

UPDATE yt_items
SET promoted_track_id = $2, expires_at = NULL, updated_at = now()
WHERE video_id = $1
`

type MarkYTPromotedParams struct {
	VideoID         string
	PromotedTrackID pgtype.UUID
}

// ---- promotion -----------------------------------------------------------------
func (q *Queries) MarkYTPromoted(ctx context.Context, arg MarkYTPromotedParams) error {
	_, err := q.db.Exec(ctx, markYTPromoted, arg.VideoID, arg.PromotedTrackID)
	return err
}

const markYTReady = `-- name: MarkYTReady :one
UPDATE yt_items
SET state = 'ready',
    blob_key = $1::text,
    bytes = $2::bigint,
    title = COALESCE(NULLIF($3::text, ''), title),
    uploader = COALESCE(NULLIF($4::text, ''), uploader),
    duration_ms = COALESCE($5::int, duration_ms),
    cached_at = now(),
    last_accessed_at = now(),
    expires_at = now() + $6::interval,
    error = NULL,
    updated_at = now()
WHERE video_id = $7
RETURNING id, video_id, title, uploader, duration_ms, thumbnail_url, state, error, blob_key, bytes, cached_at, last_accessed_at, expires_at, promoted_track_id, created_at, updated_at
`

type MarkYTReadyParams struct {
	BlobKey    string
	Bytes      int64
	Title      string
	Uploader   string
	DurationMs *int32
	Ttl        pgtype.Interval
	VideoID    string
}

// Both timestamps are computed server-side, for the same reason job scheduling
// is: the database clock is the only one that matters.
func (q *Queries) MarkYTReady(ctx context.Context, arg MarkYTReadyParams) (YtItem, error) {
	row := q.db.QueryRow(ctx, markYTReady,
		arg.BlobKey,
		arg.Bytes,
		arg.Title,
		arg.Uploader,
		arg.DurationMs,
		arg.Ttl,
		arg.VideoID,
	)
	var i YtItem
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Title,
		&i.Uploader,
		&i.DurationMs,
		&i.ThumbnailUrl,
		&i.State,
		&i.Error,
		&i.BlobKey,
		&i.Bytes,
		&i.CachedAt,
		&i.LastAccessedAt,
		&i.ExpiresAt,
		&i.PromotedTrackID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchYTItem = `-- name: TouchYTItem :exec
UPDATE yt_items
SET last_accessed_at = now(),
    expires_at = LEAST(
        now() + $1::interval,
        cached_at + $2::interval
    ),
    updated_at = now()
WHERE video_id = $3 AND state = 'ready'
`

type TouchYTItemParams struct {
	Ttl         pgtype.Interval
	MaxLifetime pgtype.Interval
	VideoID     string
}

// Sliding window: every play pushes the expiry out, capped so a single
// much-played item cannot hold cache space forever.
func (q *Queries) TouchYTItem(ctx context.Context, arg TouchYTItemParams) error {
	_, err := q.db.Exec(ctx, touchYTItem, arg.Ttl, arg.MaxLifetime, arg.VideoID)
	return err
}

const upsertYTItem = `-- name: UpsertYTItem :one
INSERT INTO yt_items (video_id, title, uploader, duration_ms, thumbnail_url)
VALUES ($1, $2, $3, $4::int, $5::text)
ON CONFLICT (video_id) DO UPDATE
SET title      = COALESCE(NULLIF(EXCLUDED.title, ''), yt_items.title),
    uploader   = COALESCE(NULLIF(EXCLUDED.uploader, ''), yt_items.uploader),
    updated_at = now()
RETURNING id, video_id, title, uploader, duration_ms, thumbnail_url, state, error, blob_key, bytes, cached_at, last_accessed_at, expires_at, promoted_track_id, created_at, updated_at
`

type UpsertYTItemParams struct {
	VideoID      string
	Title        string
	Uploader     string
	DurationMs   *int32
	ThumbnailUrl *string
}

func (q *Queries) UpsertYTItem(ctx context.Context, arg UpsertYTItemParams) (YtItem, error) {
	row := q.db.QueryRow(ctx, upsertYTItem,
		arg.VideoID,
		arg.Title,
		arg.Uploader,
		arg.DurationMs,
		arg.ThumbnailUrl,
	)
	var i YtItem
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Title,
		&i.Uploader,
		&i.DurationMs,
		&i.ThumbnailUrl,
		&i.State,
		&i.Error,
		&i.BlobKey,
		&i.Bytes,
		&i.CachedAt,
		&i.LastAccessedAt,
		&i.ExpiresAt,
		&i.PromotedTrackID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const yTCacheBytes = `-- name: YTCacheBytes :one
SELECT COALESCE(sum(bytes), 0)::bigint
FROM yt_items
WHERE state = 'ready' AND promoted_track_id IS NULL
`

func (q *Queries) YTCacheBytes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, yTCacheBytes)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const yTItemsByLRU = `-- name: YTItemsByLRU :many
SELECT id, video_id, title, uploader, duration_ms, thumbnail_url, state, error, blob_key, bytes, cached_at, last_accessed_at, expires_at, promoted_track_id, created_at, updated_at FROM yt_items
WHERE state = 'ready' AND promoted_track_id IS NULL
ORDER BY last_accessed_at
LIMIT $1
`

// Least recently used first, which is the order to reclaim space in.
func (q *Queries) YTItemsByLRU(ctx context.Context, limit int32) ([]YtItem, error) {
	rows, err := q.db.Query(ctx, yTItemsByLRU, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []YtItem{}
	for rows.Next() {
		var i YtItem
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Title,
			&i.Uploader,
			&i.DurationMs,
			&i.ThumbnailUrl,
			&i.State,
			&i.Error,
			&i.BlobKey,
			&i.Bytes,
			&i.CachedAt,
			&i.LastAccessedAt,
			&i.ExpiresAt,
			&i.PromotedTrackID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
